import type { Account, AccountType } from '@/types/accounting';
import type { TranslationKeys } from '@/i18n';

/**
 * English labels for the Angola PGC (novo com IVA) chart of accounts.
 * Codes use the no-dot scheme (main 11 → first sub 111). The stored account
 * names are Portuguese, so when the UI language is English we translate by code
 * here; any code not listed (e.g. supplier/customer or branch cash sub-accounts)
 * falls back to the stored name.
 */
export const CHART_OF_ACCOUNTS_NAMES_EN: Record<string, string> = {
  // 1 — Fixed assets / inventories
  '11': 'Tangible Fixed Assets',
  '111': 'Land and Natural Resources',
  '112': 'Buildings and Other Constructions',
  '113': 'Basic Equipment',
  '114': 'Loading and Transport Equipment',
  '115': 'Administrative Equipment',
  '116': 'Returnable Containers and Packaging',
  '119': 'Other Tangible Fixed Assets',
  '12': 'Intangible Fixed Assets',
  '121': 'Goodwill / Leasehold Transfers',
  '122': 'Research and Development Expenses',
  '123': 'Industrial Property and Other Rights and Contracts',
  '124': 'Formation Expenses',
  '129': 'Other Intangible Fixed Assets',
  '13': 'Financial Investments',
  '131': 'Subsidiary Companies',
  '132': 'Associated Companies',
  '133': 'Other Companies',
  '134': 'Investments in Real Estate',
  '135': 'Funds',
  '139': 'Other Financial Investments',
  '14': 'Fixed Assets in Progress',
  '141': 'Work in Progress',
  '142': 'Work in Progress',
  '147': 'Advances for Tangible Fixed Assets',
  '148': 'Advances for Intangible Fixed Assets',
  '149': 'Advances for Financial Investments',
  '18': 'Accumulated Depreciation',
  '181': 'Tangible Fixed Assets',
  '182': 'Intangible Fixed Assets',
  '183': 'Financial Investments in Real Estate',
  '19': 'Provisions for Financial Investments',
  '191': 'Subsidiary Companies',
  '192': 'Associated Companies',
  '21': 'Purchases',
  '211': 'Raw, Subsidiary and Consumable Materials',
  '212': 'Merchandise',
  '217': 'Purchase Returns',
  '218': 'Purchase Discounts and Rebates',
  '22': 'Raw, Subsidiary and Consumable Materials',
  '23': 'Products and Work in Progress',
  '24': 'Finished and Intermediate Products',
  '25': 'By-products, Waste, Residues and Scrap',
  '251': 'By-products',
  '252': 'Waste, Residues and Scrap',
  '26': 'Merchandise',
  '261': 'Merchandise in Stock',
  '27': 'Materials, Merchandise and Other Goods in Transit',
  '28': 'Advances on Purchases',
  '281': 'Raw Materials and Other Materials',
  '282': 'Merchandise',
  '29': 'Provision for Inventory Depreciation',
  '292': 'Raw, Subsidiary and Consumable Materials',
  '293': 'Products and Work in Progress',
  '294': 'Finished and Intermediate Products',
  '295': 'By-products, Waste, Residues and Scrap',
  '296': 'Merchandise',
  // 3 — Third parties
  '31': 'Customers',
  '311': 'Customers - Current Account',
  '312': 'Customers - Notes Receivable',
  '313': 'Customers - Discounted Notes',
  '318': 'Doubtful Customers',
  '319': 'Customers - Credit Balances',
  '32': 'Suppliers',
  '321': 'Suppliers - Current Account',
  '322': 'Suppliers - Notes Payable',
  '328': 'Suppliers - Invoices in Receipt and Verification',
  '329': 'Suppliers - Debit Balances',
  '33': 'Loans',
  '331': 'Bank Loans',
  '332': 'Bond Loans',
  '333': 'Loans through Participation Securities',
  '339': 'Other Loans Obtained',
  '34': 'State (Government)',
  '341': 'Tax on Profits',
  '342': 'Production and Consumption Tax',
  '343': 'Labour Income Tax',
  '344': 'Circulation Tax',
  '345': 'VAT',
  '3451': 'VAT Deductible',
  '3452': 'VAT Liquidated',
  '346': 'Tax Credit Certificate to Offset',
  '348': 'Price Subsidies',
  '349': 'Other Taxes',
  '35': 'Investing and Investee Entities',
  '351': 'Investing Entities',
  '36': 'Personnel',
  '361': 'Personnel - Remuneration',
  '362': 'Personnel - Profit Sharing',
  '363': 'Personnel - Advances',
  '369': 'Personnel - Other',
  '37': 'Other Receivables and Payables',
  '371': 'Purchase of Fixed Assets',
  '372': 'Sale of Fixed Assets',
  '373': 'Income to be Invoiced',
  '374': 'Charges to be Allocated to Future Periods',
  '375': 'Charges Payable',
  '376': 'Income to be Allocated to Future Periods',
  '377': 'Transitory Accounts',
  '379': 'Other Receivables and Payables',
  '38': 'Provisions for Doubtful Debts',
  '381': 'Provisions for Customers',
  '382': 'Provisions for Supplier Debit Balances',
  '383': 'Provisions for Investing and Investee Entities',
  '384': 'Provisions for Personnel Debts',
  '389': 'Provisions for Other Receivables',
  '39': 'Provisions for Other Risks and Charges',
  '391': 'Provisions for Pensions',
  '392': 'Provisions for Ongoing Legal Proceedings',
  '393': 'Provisions for Work Accidents',
  '394': 'Provisions for Guarantees Given to Customers',
  '399': 'Provisions for Other Risks and Charges',
  // 4 — Financial means
  '41': 'Negotiable Securities',
  '411': 'Shares',
  '412': 'Bonds',
  '413': 'Public Debt Securities',
  '42': 'Term Deposits',
  '421': 'National Currency',
  '422': 'Foreign Currency',
  '43': 'Demand Deposits',
  '431': 'Demand Deposits - National Currency',
  '432': 'Demand Deposits - Foreign Currency',
  '44': 'Other Deposits',
  '441': 'National Currency',
  '442': 'Foreign Currency',
  '45': 'Cash',
  '451': 'Petty Cash (Fixed Fund)',
  '452': 'Values to Deposit',
  '453': 'Values for Specific Payments',
  // 5 — Equity
  '51': 'Capital',
  '52': 'Own Shares / Quotas',
  '521': 'Nominal Value',
  '522': 'Discounts',
  '523': 'Premiums',
  '53': 'Issue Premiums',
  '54': 'Supplementary Capital Contributions',
  '55': 'Legal Reserves',
  '56': 'Revaluation Reserves',
  '561': 'Legal',
  '562': 'Autonomous',
  '57': 'Reserves for Special Purposes',
  '58': 'Free Reserves',
  // 6 — Income
  '61': 'Sales',
  '611': 'Finished and Intermediate Products',
  '612': 'By-products, Waste, Residues and Scrap',
  '613': 'Merchandise',
  '614': 'Consumable Packaging',
  '615': 'Price Subsidies',
  '617': 'Returns',
  '618': 'Discounts and Rebates',
  '619': 'Transfer to Operating Results',
  '62': 'Services Rendered',
  '621': 'Main Services',
  '622': 'Secondary Services',
  '628': 'Discounts and Rebates',
  '629': 'Transfer to Operating Results',
  '63': 'Other Operating Income',
  '631': 'Supplementary Services',
  '632': 'Royalties',
  '633': 'Operating Subsidies',
  '634': 'Investment Subsidies',
  '635': 'VAT',
  '638': 'Other Operating Income and Gains',
  '639': 'Transfer to Operating Results',
  '64': 'Change in Inventories of Finished Products and Work in Progress',
  '641': 'Products and Work in Progress',
  '642': 'Finished Products',
  '643': 'Intermediate Products',
  '649': 'Transfer to Operating Results',
  '65': 'Own Work Capitalised',
  '651': 'For Fixed Assets',
  '652': 'For Charges to be Allocated to Future Periods',
  '659': 'Transfer to Operating Results',
  '66': 'General Financial Income and Gains',
  '661': 'Interest',
  '662': 'Favourable Exchange Differences',
  '663': 'Prompt Payment Discounts Obtained',
  '664': 'Income from Real Estate Investments',
  '665': 'Income from Capital Holdings',
  '666': 'Gains on Disposal of Financial Investments',
  '667': 'Reduction of Provisions',
  '67': 'Financial Income and Gains in Subsidiaries and Associates',
  '671': 'Income from Capital Holdings',
  '679': 'Transfer to Results in Subsidiaries and Associates',
  '68': 'Other Non-Operating Income and Gains',
  '681': 'Reduction of Provisions',
  '6810': 'Corrections Relating to Prior Periods',
  '6811': 'Other Non-Operating Gains and Losses',
  '682': 'Reversal of Extraordinary Depreciation',
  '684': 'Gains on Inventories',
  '685': 'Recovery of Debts',
  '686': 'Benefits from Contractual Penalties',
  '688': 'Discontinuance of Operations',
  '689': 'Changes in Accounting Policies',
  '69': 'Extraordinary Income and Gains',
  '691': 'Gains from Natural Disasters',
  '692': 'Gains from Political Upheavals',
  '693': 'Gains from Expropriations',
  '694': 'Gains from Claims / Losses',
  '695': 'Subsidies',
  '696': 'Reversal of Non-Payable Liabilities',
  '699': 'Transfer to Extraordinary Results',
  // 7 — Costs
  '71': 'Cost of Inventories Sold',
  '711': 'Cost of Merchandise Sold',
  '72': 'Personnel Costs',
  '721': 'Remuneration - Governing Bodies',
  '722': 'Remuneration - Personnel',
  '723': 'Pensions',
  '724': 'Pension Premiums',
  '73': 'Depreciation for the Period',
  '731': 'Tangible Fixed Assets',
  '732': 'Intangible Fixed Assets',
  '739': 'Transfer to Operating Results',
  '75': 'Other Operating Costs and Losses',
  '751': 'Subcontracts',
  '752': 'Third-Party Supplies and Services',
  '753': 'Taxes',
  '754': 'Confidential Expenses',
  '755': 'Membership Fees',
  '756': 'Gifts and Samples of Inventory',
  '758': 'Other Operating Costs and Losses',
  '759': 'Transfer to Operating Results',
  '76': 'General Financial Costs and Losses',
  '761': 'Interest',
  '762': 'Unfavourable Exchange Differences',
  '766': 'Losses on Disposal of Financial Investments',
  '767': 'Bank Services',
  '769': 'Transfer to Financial Results',
  '77': 'Financial Costs and Losses in Subsidiaries and Associates',
  '779': 'Transfer to Financial Results',
  '78': 'Other Non-Operating Costs and Losses',
  '781': 'Provisions for the Period',
  '7810': 'Corrections Relating to Prior Periods',
  '7811': 'Other Non-Operating Costs and Losses',
  '7819': 'Transfer to Non-Operating Results',
  '782': 'Extraordinary Depreciation',
  '783': 'Losses on Fixed Assets',
  '784': 'Losses on Inventories',
  '785': 'Bad Debts',
  '786': 'Fines and Contractual Penalties',
  '787': 'Restructuring Cost',
  '788': 'Discontinuance of Operations',
  '789': 'Changes in Accounting Policies',
  '79': 'Extraordinary Costs and Losses',
  '791': 'Losses from Natural Disasters',
  '792': 'Losses from Political Upheavals',
  '793': 'Losses from Expropriations',
  '794': 'Losses from Claims / Losses',
  '799': 'Transfer to Extraordinary Results',
  // 8 — Results
  '81': 'Retained Earnings',
  '811': 'Year',
  '812': 'Year',
  '82': 'Operating Results',
  '821': 'Sales',
  '8219': 'Transfer to Net Results',
  '822': 'Services Rendered',
  '823': 'Other Operating Income',
  '824': 'Change in Inventories of Finished Products and Work in Progress',
  '825': 'Own Work Capitalised',
  '826': 'Cost of Merchandise Sold and Materials Consumed',
  '827': 'Personnel Costs',
  '828': 'Depreciation for the Period',
  '829': 'Other Operating Costs',
  '83': 'Financial Results',
  '831': 'General Financial Income and Gains',
  '832': 'General Financial Costs and Losses',
  '839': 'Transfer to Net Results',
  '84': 'Financial Results in Subsidiaries and Associates',
  '841': 'Income and Gains in Subsidiaries and Associates',
  '842': 'Costs and Losses in Subsidiaries and Associates',
  '849': 'Transfer to Net Results',
  '85': 'Non-Operating Results',
  '851': 'Non-Operating Income and Gains',
  '852': 'Non-Operating Costs and Losses',
  '859': 'Transfer to Net Results',
  '86': 'Extraordinary Results',
  '861': 'Extraordinary Income and Gains',
  '862': 'Extraordinary Costs and Losses',
  '869': 'Transfer to Net Results',
  '87': 'Taxes on Profits',
  '871': 'Tax on Current Results',
  '872': 'Tax on Extraordinary Results',
  '879': 'Transfer to Net Results',
  '88': 'Net Result for the Period',
  '881': 'Operating Results',
  '882': 'General Financial Results',
  '883': 'Results in Subsidiaries and Associates',
  '884': 'Non-Operating Results',
  '885': 'Tax on Current Results',
  '886': 'Extraordinary Results',
  '887': 'Tax on Extraordinary Results',
  '889': 'Transfer to Retained Earnings',
  '89': 'Advance Dividends',
  '899': 'Transfer to Retained Earnings',
};

const CASH_BRANCH_RE = /^Caixa\s*-\s*(.+)$/i;

export function resolveAccountDisplayName(
  account: Pick<Account, 'code' | 'name'>,
  language: 'en' | 'pt',
  t?: Pick<TranslationKeys, 'chartOfAccountsUi'>,
): string {
  // Portuguese: the stored PGC names are already in Portuguese.
  if (language !== 'en') return account.name;

  const mapped = CHART_OF_ACCOUNTS_NAMES_EN[account.code];
  if (mapped) return mapped;

  // Dynamic per-branch cash accounts are stored as "Caixa - <branch>".
  if (t) {
    const cashMatch = account.name.match(CASH_BRANCH_RE);
    if (cashMatch) {
      return `${t.chartOfAccountsUi.cashBranchPrefix}${cashMatch[1].trim()}`;
    }
  }

  return account.name;
}

export function resolveAccountTypeLabel(type: AccountType, t: TranslationKeys): string {
  const labels: Record<AccountType, string> = {
    asset: t.chartOfAccountsUi.typeAsset,
    liability: t.chartOfAccountsUi.typeLiability,
    equity: t.chartOfAccountsUi.typeEquity,
    revenue: t.chartOfAccountsUi.typeRevenue,
    expense: t.chartOfAccountsUi.typeExpense,
  };
  return labels[type] ?? type;
}
