import type { Account, AccountType } from '@/types/accounting';
import type { TranslationKeys } from '@/i18n';

/** Standard Angolan chart-of-accounts codes seeded in the backend (migration 003+). */
export const CHART_OF_ACCOUNTS_NAMES_EN: Record<string, string> = {
  '1': 'Fixed Assets and Investments',
  '1.1': 'Tangible Fixed Assets',
  '1.1.1': 'Land',
  '1.1.2': 'Buildings',
  '1.1.3': 'Basic Equipment',
  '1.1.4': 'Transport Equipment',
  '1.1.5': 'Office Equipment',
  '1.2': 'Intangible Fixed Assets',
  '1.2.1': 'Goodwill / Lease Rights',
  '1.2.2': 'Software',
  '2': 'Inventories',
  '2.1': 'Purchases',
  '2.1.1': 'Merchandise',
  '2.1.2': 'Raw Materials',
  '2.2': 'Merchandise',
  '2.3': 'Finished Products',
  '3': 'Third Parties',
  '3.1': 'Customers',
  '3.1.1': 'Customers - Current Account',
  '3.1.2': 'Customers - Notes Receivable',
  '3.2': 'Suppliers',
  '3.2.1': 'Suppliers - Current Account',
  '3.2.2': 'Suppliers - Notes Payable',
  '3.3': 'State and Other Public Entities',
  '3.3.1': 'VAT',
  '3.3.2': 'Income Tax',
  '3.4': 'Staff',
  '3.4.1': 'Salaries Payable',
  '4': 'Monetary Assets',
  '4.1': 'Cash',
  '4.1.1': 'Main Cash',
  '4.1.2': 'Petty Cash (Imprest Fund)',
  '4.2': 'Demand Deposits',
  '4.2.1': 'Main Bank Account',
  '5': 'Equity',
  '5.1': 'Share Capital',
  '5.2': 'Reserves',
  '5.2.1': 'Legal Reserves',
  '5.2.2': 'Other Reserves',
  '5.3': 'Retained Earnings',
  '5.4': 'Net Income for the Period',
  '6': 'Expenses and Losses',
  '6.1': 'Cost of Goods Sold',
  '6.2': 'External Supplies and Services',
  '6.2.1': 'Electricity',
  '6.2.2': 'Water',
  '6.2.3': 'Communications',
  '6.2.4': 'Insurance',
  '6.2.5': 'Rent and Leases',
  '6.2.6': 'Freight on Purchases',
  '6.3': 'Staff Expenses',
  '6.3.1': 'Salaries',
  '6.3.2': 'Social Charges',
  '6.4': 'Depreciation and Amortization',
  '6.5': 'Financial Expenses',
  '6.5.1': 'Interest Paid',
  '6.5.2': 'Unfavorable Exchange Differences',
  '6.6': 'Taxes',
  '6.6.1': 'Inventory Losses and Breakage',
  '7': 'Income and Gains',
  '7.1': 'Sales',
  '7.1.1': 'Merchandise Sales',
  '7.1.2': 'Product Sales',
  '7.2': 'Services Rendered',
  '7.3': 'Financial Income',
  '7.3.1': 'Interest Earned',
  '7.3.2': 'Favorable Exchange Differences',
  '7.4': 'Other Income',
};

export const CHART_OF_ACCOUNTS_NAMES_PT: Record<string, string> = {
  '1': 'Meios Fixos e Investimentos',
  '1.1': 'Imobilizações Corpóreas',
  '1.1.1': 'Terrenos',
  '1.1.2': 'Edifícios',
  '1.1.3': 'Equipamentos Básicos',
  '1.1.4': 'Equipamentos de Transporte',
  '1.1.5': 'Equipamentos Administrativos',
  '1.2': 'Imobilizações Incorpóreas',
  '1.2.1': 'Trespasses',
  '1.2.2': 'Software',
  '2': 'Existências',
  '2.1': 'Compras',
  '2.1.1': 'Mercadorias',
  '2.1.2': 'Matérias-Primas',
  '2.2': 'Mercadorias',
  '2.3': 'Produtos Acabados',
  '3': 'Terceiros',
  '3.1': 'Clientes',
  '3.1.1': 'Clientes c/c',
  '3.1.2': 'Clientes - Títulos a Receber',
  '3.2': 'Fornecedores',
  '3.2.1': 'Fornecedores c/c',
  '3.2.2': 'Fornecedores - Títulos a Pagar',
  '3.3': 'Estado e Outros Entes Públicos',
  '3.3.1': 'IVA',
  '3.3.2': 'Imposto sobre Rendimentos',
  '3.4': 'Pessoal',
  '3.4.1': 'Remunerações a Pagar',
  '4': 'Meios Monetários',
  '4.1': 'Caixa',
  '4.1.1': 'Caixa Principal',
  '4.1.2': 'Caixa Pequena (Fundo de Maneio)',
  '4.2': 'Depósitos à Ordem',
  '4.2.1': 'Banco Principal',
  '5': 'Capital Próprio',
  '5.1': 'Capital Social',
  '5.2': 'Reservas',
  '5.2.1': 'Reservas Legais',
  '5.2.2': 'Outras Reservas',
  '5.3': 'Resultados Transitados',
  '5.4': 'Resultado Líquido do Exercício',
  '6': 'Gastos e Perdas',
  '6.1': 'Custo das Mercadorias Vendidas',
  '6.2': 'Fornecimentos e Serviços Externos',
  '6.2.1': 'Electricidade',
  '6.2.2': 'Água',
  '6.2.3': 'Comunicações',
  '6.2.4': 'Seguros',
  '6.2.5': 'Rendas e Alugueres',
  '6.2.6': 'Transporte sobre Compras',
  '6.3': 'Gastos com Pessoal',
  '6.3.1': 'Remunerações',
  '6.3.2': 'Encargos Sociais',
  '6.4': 'Amortizações e Depreciações',
  '6.5': 'Gastos Financeiros',
  '6.5.1': 'Juros Suportados',
  '6.5.2': 'Diferenças de Câmbio Desfavoráveis',
  '6.6': 'Impostos',
  '6.6.1': 'Perdas e Quebras de Inventário',
  '7': 'Rendimentos e Ganhos',
  '7.1': 'Vendas',
  '7.1.1': 'Vendas de Mercadorias',
  '7.1.2': 'Vendas de Produtos',
  '7.2': 'Prestações de Serviços',
  '7.3': 'Rendimentos Financeiros',
  '7.3.1': 'Juros Obtidos',
  '7.3.2': 'Diferenças de Câmbio Favoráveis',
  '7.4': 'Outros Rendimentos',
};

const CASH_BRANCH_RE = /^Caixa\s*-\s*(.+)$/i;

export function resolveAccountDisplayName(
  account: Pick<Account, 'code' | 'name'>,
  language: 'en' | 'pt',
  t?: Pick<TranslationKeys, 'chartOfAccountsUi'>,
): string {
  const byCode = language === 'en' ? CHART_OF_ACCOUNTS_NAMES_EN : CHART_OF_ACCOUNTS_NAMES_PT;
  const mapped = byCode[account.code];
  if (mapped) return mapped;

  if (language === 'en' && t) {
    const cashMatch = account.name.match(CASH_BRANCH_RE);
    if (cashMatch) {
      return `${t.chartOfAccountsUi.cashBranchPrefix}${cashMatch[1].trim()}`;
    }
  }

  return account.name;
}

export function resolveAccountTypeLabel(type: AccountType, t: TranslationKeys): string {
  const labels: Record<AccountType, string> = {
    asset: t.chartOfAccountsUi.typeAsset,
    liability: t.chartOfAccountsUi.typeLiability,
    equity: t.chartOfAccountsUi.typeEquity,
    revenue: t.chartOfAccountsUi.typeRevenue,
    expense: t.chartOfAccountsUi.typeExpense,
  };
  return labels[type] ?? type;
}
