import type { Product } from '@/types/erp';
import { readProductStock } from '@/lib/inventoryGrid';

export type CanonicalSkuAggregates = {
  stock: number;
  price: number;
  cost: number;
  firstCost: number;
  lastCost: number;
  avgCost: number;
};

/** Max stock/price/cost across every row sharing a canonical SKU (catalog + filial). */
export function buildCanonicalSkuAggregates(products: Product[]): Map<string, CanonicalSkuAggregates> {
  const bySku = new Map<string, CanonicalSkuAggregates>();
  for (const p of products) {
    const key = canonicalProductSku(p.sku).toLowerCase();
    if (!key) continue;
    const cur = bySku.get(key) || {
      stock: 0,
      price: 0,
      cost: 0,
      firstCost: 0,
      lastCost: 0,
      avgCost: 0,
    };
    cur.stock = Math.max(cur.stock, readProductStock(p));
    cur.price = Math.max(cur.price, Number(p.price) || 0);
    cur.cost = Math.max(cur.cost, Number(p.cost) || 0);
    cur.firstCost = Math.max(cur.firstCost, Number(p.firstCost) || 0);
    cur.lastCost = Math.max(cur.lastCost, Number(p.lastCost) || 0);
    cur.avgCost = Math.max(cur.avgCost, Number(p.avgCost) || 0);
    bySku.set(key, cur);
  }
  return bySku;
}

export function applyCanonicalSkuAggregates(
  product: Product,
  agg: CanonicalSkuAggregates,
): Product {
  return {
    ...product,
    stock: Math.max(readProductStock(product), agg.stock),
    price: Math.max(Number(product.price) || 0, agg.price),
    cost: Math.max(Number(product.cost) || 0, agg.cost),
    firstCost: Math.max(Number(product.firstCost) || 0, agg.firstCost),
    lastCost: Math.max(Number(product.lastCost) || 0, agg.lastCost),
    avgCost: Math.max(Number(product.avgCost) || 0, agg.avgCost),
  };
}

const DUP_SKU_SUFFIX_RE = /-DUP-[a-f0-9]+$/i;

/** Canonical SKU (strip legacy *-DUP-* repair suffix). */
export function canonicalProductSku(sku?: string | null): string {
  const raw = String(sku ?? '').trim();
  if (!raw) return '';
  const base = raw.replace(DUP_SKU_SUFFIX_RE, '').trim();
  return base || raw;
}

export function normalizeProductSkuKey(sku?: string | null): string {
  return canonicalProductSku(sku).toLowerCase();
}

export function normalizeProductNameKey(name?: string | null): string {
  return String(name ?? '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ');
}

export function normalizeProductBarcodeKey(barcode?: string | null): string {
  return String(barcode ?? '').trim().toLowerCase();
}

/** Shared catalog (NULL) and sede/main branch rows belong to the same product scope. */
export function normalizeProductBranchScopeKey(
  branchId?: string | null,
  catalogBranchIds: string[] = [],
): string {
  const value = String(branchId ?? '').trim();
  if (!value || value === 'all') return 'catalog';
  if (catalogBranchIds.some((id) => String(id) === value)) return 'catalog';
  return value;
}

export function isCatalogBranchScope(
  branchId?: string | null,
  catalogBranchIds: string[] = [],
): boolean {
  return normalizeProductBranchScopeKey(branchId, catalogBranchIds) === 'catalog';
}

export function skuLooksAutoGenerated(sku?: string | null): boolean {
  const value = String(sku ?? '').trim();
  if (!value) return true;
  return /^AUTO-/i.test(value) || /^SKU-\d{10,}/i.test(value);
}

function rowScore(row: Product, branchId?: string, catalogBranchIds: string[] = []): number {
  let score = Number(row.stock || 0) * 1000;
  if (branchId && String(row.branchId || '') === String(branchId)) score += 1_000_000;
  if (normalizeProductBranchScopeKey(row.branchId, catalogBranchIds) === 'catalog' && !String(row.branchId || '').trim()) {
    score += 500;
  }
  if (String(row.branchId || '').trim()) score += 100;
  if (!skuLooksAutoGenerated(row.sku)) score += 50;
  if (String(row.barcode || '').trim()) score += 25;
  return score;
}

function pickPreferredRow(
  a: Product,
  b: Product,
  branchId?: string,
  catalogBranchIds: string[] = [],
): Product {
  const left = rowScore(a, branchId, catalogBranchIds);
  const right = rowScore(b, branchId, catalogBranchIds);
  if (left === right) {
    const aTime = String(a.createdAt || '');
    const bTime = String(b.createdAt || '');
    return aTime <= bTime ? a : b;
  }
  return left >= right ? a : b;
}

function mergeProductRows(
  a: Product,
  b: Product,
  branchId?: string,
  catalogBranchIds: string[] = [],
): Product {
  const pick = pickPreferredRow(a, b, branchId, catalogBranchIds);
  const other = pick === a ? b : a;
  const mergeNum = (a?: number, b?: number) => Math.max(Number(a) || 0, Number(b) || 0);
  return {
    ...pick,
    stock: mergeNum(readProductStock(pick), readProductStock(other)),
    price: mergeNum(pick.price, other.price),
    cost: mergeNum(pick.cost, other.cost),
    firstCost: mergeNum(pick.firstCost, other.firstCost),
    lastCost: mergeNum(pick.lastCost, other.lastCost),
    avgCost: mergeNum(pick.avgCost, other.avgCost),
  };
}

export function shouldMergeProductDuplicates(
  a: Product,
  b: Product,
  catalogBranchIds: string[] = [],
): boolean {
  const nameA = normalizeProductNameKey(a.name);
  const nameB = normalizeProductNameKey(b.name);
  if (!nameA || nameA !== nameB) return false;

  const branchA = normalizeProductBranchScopeKey(a.branchId, catalogBranchIds);
  const branchB = normalizeProductBranchScopeKey(b.branchId, catalogBranchIds);
  if (branchA !== branchB) return false;

  const skuA = normalizeProductSkuKey(a.sku);
  const skuB = normalizeProductSkuKey(b.sku);
  if (skuA && skuB && skuA === skuB) return true;

  const barcodeA = normalizeProductBarcodeKey(a.barcode);
  const barcodeB = normalizeProductBarcodeKey(b.barcode);
  if (barcodeA && barcodeB && barcodeA === barcodeB) return true;

  if (skuLooksAutoGenerated(a.sku) || skuLooksAutoGenerated(b.sku)) return true;

  // Same name in the same branch scope (e.g. "water" with W001 vs SKU-173…)
  return true;
}

function dedupeKey(product: Product, catalogBranchIds: string[]): string {
  const scope = normalizeProductBranchScopeKey(product.branchId, catalogBranchIds);
  const skuKey = normalizeProductSkuKey(product.sku);
  if (skuKey && !skuLooksAutoGenerated(product.sku)) {
    return `${scope}|sku:${skuKey}`;
  }
  const nameKey = normalizeProductNameKey(product.name);
  return `${scope}|name:${nameKey || product.id}`;
}

/** One row per SKU per branch scope; collapse obvious duplicate names (incl. sede/catalog). */
export function dedupeProductsForDisplay(
  products: Product[],
  branchId?: string,
  catalogBranchIds: string[] = [],
): Product[] {
  const bySku = new Map<string, Product>();
  for (const product of products) {
    const key = dedupeKey(product, catalogBranchIds);
    const prev = bySku.get(key);
    if (!prev) {
      bySku.set(key, product);
      continue;
    }
    bySku.set(key, mergeProductRows(prev, product, branchId, catalogBranchIds));
  }

  const merged: Product[] = [];
  for (const product of bySku.values()) {
    const index = merged.findIndex((row) => shouldMergeProductDuplicates(row, product, catalogBranchIds));
    if (index < 0) {
      merged.push(product);
      continue;
    }
    merged[index] = mergeProductRows(merged[index], product, branchId, catalogBranchIds);
  }
  return merged;
}
