import type { Product } from '@/types/erp';

export function normalizeProductSkuKey(sku?: string | null): string {
  return String(sku ?? '').trim().toLowerCase();
}

export function normalizeProductNameKey(name?: string | null): string {
  return String(name ?? '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ');
}

export function normalizeProductBarcodeKey(barcode?: string | null): string {
  return String(barcode ?? '').trim().toLowerCase();
}

/** Shared catalog (NULL) and sede/main branch rows belong to the same product scope. */
export function normalizeProductBranchScopeKey(
  branchId?: string | null,
  catalogBranchIds: string[] = [],
): string {
  const value = String(branchId ?? '').trim();
  if (!value || value === 'all') return 'catalog';
  if (catalogBranchIds.some((id) => String(id) === value)) return 'catalog';
  return value;
}

export function isCatalogBranchScope(
  branchId?: string | null,
  catalogBranchIds: string[] = [],
): boolean {
  return normalizeProductBranchScopeKey(branchId, catalogBranchIds) === 'catalog';
}

export function skuLooksAutoGenerated(sku?: string | null): boolean {
  const value = String(sku ?? '').trim();
  if (!value) return true;
  return /^AUTO-/i.test(value) || /^SKU-\d{10,}/i.test(value);
}

function rowScore(row: Product, branchId?: string, catalogBranchIds: string[] = []): number {
  let score = Number(row.stock || 0) * 1000;
  if (branchId && String(row.branchId || '') === String(branchId)) score += 1_000_000;
  if (normalizeProductBranchScopeKey(row.branchId, catalogBranchIds) === 'catalog' && !String(row.branchId || '').trim()) {
    score += 500;
  }
  if (String(row.branchId || '').trim()) score += 100;
  if (!skuLooksAutoGenerated(row.sku)) score += 50;
  if (String(row.barcode || '').trim()) score += 25;
  return score;
}

function pickPreferredRow(
  a: Product,
  b: Product,
  branchId?: string,
  catalogBranchIds: string[] = [],
): Product {
  const left = rowScore(a, branchId, catalogBranchIds);
  const right = rowScore(b, branchId, catalogBranchIds);
  if (left === right) {
    const aTime = String(a.createdAt || '');
    const bTime = String(b.createdAt || '');
    return aTime <= bTime ? a : b;
  }
  return left >= right ? a : b;
}

export function shouldMergeProductDuplicates(
  a: Product,
  b: Product,
  catalogBranchIds: string[] = [],
): boolean {
  const nameA = normalizeProductNameKey(a.name);
  const nameB = normalizeProductNameKey(b.name);
  if (!nameA || nameA !== nameB) return false;

  const branchA = normalizeProductBranchScopeKey(a.branchId, catalogBranchIds);
  const branchB = normalizeProductBranchScopeKey(b.branchId, catalogBranchIds);
  if (branchA !== branchB) return false;

  const skuA = normalizeProductSkuKey(a.sku);
  const skuB = normalizeProductSkuKey(b.sku);
  if (skuA && skuB && skuA === skuB) return true;

  const barcodeA = normalizeProductBarcodeKey(a.barcode);
  const barcodeB = normalizeProductBarcodeKey(b.barcode);
  if (barcodeA && barcodeB && barcodeA === barcodeB) return true;

  return skuLooksAutoGenerated(a.sku) || skuLooksAutoGenerated(b.sku);
}

function dedupeKey(product: Product, catalogBranchIds: string[]): string {
  const scope = normalizeProductBranchScopeKey(product.branchId, catalogBranchIds);
  const skuKey = normalizeProductSkuKey(product.sku) || product.id;
  return `${scope}|${skuKey}`;
}

/** One row per SKU per branch scope; collapse obvious duplicate names (incl. sede/catalog). */
export function dedupeProductsForDisplay(
  products: Product[],
  branchId?: string,
  catalogBranchIds: string[] = [],
): Product[] {
  const bySku = new Map<string, Product>();
  for (const product of products) {
    const key = dedupeKey(product, catalogBranchIds);
    const prev = bySku.get(key);
    if (!prev) {
      bySku.set(key, product);
      continue;
    }
    bySku.set(key, pickPreferredRow(prev, product, branchId, catalogBranchIds));
  }

  const merged: Product[] = [];
  for (const product of bySku.values()) {
    const index = merged.findIndex((row) => shouldMergeProductDuplicates(row, product, catalogBranchIds));
    if (index < 0) {
      merged.push(product);
      continue;
    }
    merged[index] = pickPreferredRow(merged[index], product, branchId, catalogBranchIds);
  }
  return merged;
}
