export const COLUMN_AUTO_MATCH_PATTERNS: Record<string, string[]> = {
  codigo: ['código', 'codigo', 'sku', 'ref', 'referencia', 'referência', 'code', 'id'],
  descricao: ['descrição', 'descricao', 'nome', 'produto', 'name', 'description', 'item'],
  preco: ['preço', 'preco', 'preço venda', 'preco venda', 'price', 'pvp', 'valor'],
  custo: ['custo', 'preço custo', 'preco custo', 'cost', 'valor custo'],
  quantidade: ['quantidade', 'qty', 'qtd', 'stock', 'estoque'],
  unidade: ['unidade', 'un', 'unit', 'uom'],
  categoria: ['categoria', 'category', 'família', 'familia', 'family', 'grupo', 'group'],
  iva: ['iva', 'imposto', 'tax', '%'],
  codigoBarras: ['código barras', 'codigo barras', 'barcode', 'ean', 'gtin'],
  fornecedor: ['fornecedor', 'supplier', 'vendor'],
  qtdMinima: ['qtd mínima', 'qtd minima', 'min qty', 'minimo', 'mínimo'],
  localizacao: ['localização', 'localizacao', 'location', 'armazém', 'armazem'],
  nome: ['nome', 'name', 'razão social', 'razao social', 'empresa'],
  nif: ['nif', 'contribuinte', 'vat', 'tax id', 'cnpj', 'cpf'],
  telefone: ['telefone', 'tel', 'phone', 'celular', 'mobile', 'contacto'],
  email: ['email', 'e-mail', 'correio'],
  morada: ['morada', 'endereço', 'endereco', 'address', 'rua'],
  cidade: ['cidade', 'city', 'localidade'],
  pais: ['país', 'pais', 'country'],
  limiteCredito: ['limite crédito', 'limite credito', 'credit limit', 'crédito'],
  pessoaContacto: ['pessoa contacto', 'contacto', 'contact', 'contact person'],
  prazoPagamento: ['prazo pagamento', 'payment terms', 'prazo'],
  notas: ['notas', 'notes', 'observações', 'obs'],
};

