-- 045_pgc_novo_com_iva.sql
-- Replace the chart of accounts with the Angola PGC (novo com IVA).
-- Mains (orange in the source spreadsheet) are level-1 headers; their direct
-- sub-accounts (blue) are level-2 leaves. Numbering is dot-less (main 11 -> sub 111).
-- IVA keeps the dedutivel/liquidado split (3451/3452) for AGT/SAF-T.

-- 1) Deactivate the previous default chart only when the dotted PGC is present
--    and the new no-dot PGC has not been seeded yet (idempotent / safe to re-run).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM chart_of_accounts WHERE code = '7.1')
     AND NOT EXISTS (SELECT 1 FROM chart_of_accounts WHERE code = '61') THEN
    UPDATE chart_of_accounts SET is_active = false;
  END IF;
END $$;

-- 2) Upsert every PGC account as active.
INSERT INTO chart_of_accounts (code, name, account_type, account_nature, level, is_header, is_active) VALUES
  ('11', 'IMOBILIZAÇÕES CORPÓREAS', 'asset', 'debit', 1, true, true),
  ('111', 'Terreno e recursos naturais', 'asset', 'debit', 2, false, true),
  ('112', 'Edifícios e outras construções', 'asset', 'debit', 2, false, true),
  ('113', 'Equipamento básico', 'asset', 'debit', 2, false, true),
  ('114', 'Equipamento de carga e transporte', 'asset', 'debit', 2, false, true),
  ('115', 'Equipamento administrativo', 'asset', 'debit', 2, false, true),
  ('116', 'Taras e vasilhame', 'asset', 'debit', 2, false, true),
  ('119', 'Outras imobilizações corpóreas', 'asset', 'debit', 2, false, true),
  ('12', 'IMOBILIZAÇÕES INCORPÓREAS', 'asset', 'debit', 1, true, true),
  ('121', 'Trespasses', 'asset', 'debit', 2, false, true),
  ('122', 'Despesas de investigação e desenvolvimento', 'asset', 'debit', 2, false, true),
  ('123', 'Propriedade industrial e outros direitos e contratos', 'asset', 'debit', 2, false, true),
  ('124', 'Despesas de constituição', 'asset', 'debit', 2, false, true),
  ('129', 'Outras imobilizações incorpóreas', 'asset', 'debit', 2, false, true),
  ('13', 'INVESTIMENTOS FINANCEIROS', 'asset', 'debit', 1, true, true),
  ('131', 'Empresas subsidiárias', 'asset', 'debit', 2, false, true),
  ('132', 'Empresas associadas', 'asset', 'debit', 2, false, true),
  ('133', 'Outras empresas', 'asset', 'debit', 2, false, true),
  ('134', 'Investimentos em imóveis', 'asset', 'debit', 2, false, true),
  ('135', 'Fundos', 'asset', 'debit', 2, false, true),
  ('139', 'Outros investimentos financeiros', 'asset', 'debit', 2, false, true),
  ('14', 'IMOBILIZAÇÕES EM CURSO', 'asset', 'debit', 1, true, true),
  ('141', 'Obra em curso', 'asset', 'debit', 2, false, true),
  ('142', 'Obra em curso', 'asset', 'debit', 2, false, true),
  ('147', 'Adiantamentos por conta de imobilizado corpóreo', 'asset', 'debit', 2, false, true),
  ('148', 'Adiantamentos por conta de imobilizado incorpóreo', 'asset', 'debit', 2, false, true),
  ('149', 'Adiantamentos por conta de investimentos financeiros', 'asset', 'debit', 2, false, true),
  ('18', 'AMORTIZAÇÕES ACUMULADAS', 'asset', 'credit', 1, true, true),
  ('181', 'Imobilizações corpóreas', 'asset', 'credit', 2, false, true),
  ('182', 'Imobilizações incorpóreas', 'asset', 'credit', 2, false, true),
  ('183', 'Investimentos financeiros em imóveis', 'asset', 'credit', 2, false, true),
  ('19', 'PROVISÕES PARA INVESTIMENTOS FINANCEIROS', 'asset', 'credit', 1, true, true),
  ('191', 'Empresas subsidiárias', 'asset', 'credit', 2, false, true),
  ('192', 'Empresas associadas', 'asset', 'credit', 2, false, true),
  ('21', 'COMPRAS', 'asset', 'debit', 1, true, true),
  ('211', 'Matérias-primas, subsidiárias e de consumo', 'asset', 'debit', 2, false, true),
  ('212', 'Mercadorias', 'asset', 'debit', 2, false, true),
  ('217', 'Devoluções de compras', 'asset', 'debit', 2, false, true),
  ('218', 'Descontos e abatimentos em compras', 'asset', 'debit', 2, false, true),
  ('22', 'MATÉRIAS-PRIMAS, SUBSIDIÁRIAS E DE CONSUMO', 'asset', 'debit', 1, true, true),
  ('23', 'PRODUTOS E TRABALHOS EM CURSO', 'asset', 'debit', 1, true, true),
  ('24', 'PRODUTOS ACABADOS E INTERMÉDIOS', 'asset', 'debit', 1, true, true),
  ('25', 'SUBPRODUTOS, DESPERDÍCIOS, RESÍDUOS E REFUGOS', 'asset', 'debit', 1, true, true),
  ('251', 'Subprodutos', 'asset', 'debit', 2, false, true),
  ('252', 'Desperdícios, resíduos e refugos', 'asset', 'debit', 2, false, true),
  ('26', 'MERCADORIAS', 'asset', 'debit', 1, true, true),
  ('261', 'Mercadorias em armazém', 'asset', 'debit', 2, false, true),
  ('27', 'MATÉRIAS, MERCADORIAS E OUTROS MATERIAIS EM TRÂNSITO', 'asset', 'debit', 1, true, true),
  ('28', 'ADIANTAMENTOS POR CONTA DE COMPRAS', 'asset', 'debit', 1, true, true),
  ('281', 'Matérias-primas e outros materiais', 'asset', 'debit', 2, false, true),
  ('282', 'Mercadorias', 'asset', 'debit', 2, false, true),
  ('29', 'PROVISÃO PARA DEPRECIAÇÃO DE EXISTÊNCIAS', 'asset', 'credit', 1, true, true),
  ('292', 'Matérias-primas, subsidiárias e de consumo', 'asset', 'credit', 2, false, true),
  ('293', 'Produtos e trabalhos em curso', 'asset', 'credit', 2, false, true),
  ('294', 'Produtos acabados e intermédios', 'asset', 'credit', 2, false, true),
  ('295', 'Subprodutos, desperdícios, resíduos e refugos', 'asset', 'credit', 2, false, true),
  ('296', 'Mercadorias', 'asset', 'credit', 2, false, true),
  ('31', 'CLIENTES', 'asset', 'debit', 1, true, true),
  ('311', 'Clientes - correntes', 'asset', 'debit', 2, false, true),
  ('312', 'Clientes - títulos a receber', 'asset', 'debit', 2, false, true),
  ('313', 'Clientes - títulos descontados', 'asset', 'debit', 2, false, true),
  ('318', 'Clientes de cobrança duvidosa', 'asset', 'debit', 2, false, true),
  ('319', 'Clientes - saldos credores', 'asset', 'debit', 2, false, true),
  ('32', 'FORNECEDORES', 'liability', 'credit', 1, true, true),
  ('321', 'Fornecedores - correntes', 'liability', 'credit', 2, false, true),
  ('322', 'Fornecedores - títulos a pagar', 'liability', 'credit', 2, false, true),
  ('328', 'Fornecedores - facturas em recepção e conferência', 'liability', 'credit', 2, false, true),
  ('329', 'Fornecedores - saldos devedores', 'liability', 'credit', 2, false, true),
  ('33', 'EMPRÉSTIMOS', 'liability', 'credit', 1, true, true),
  ('331', 'Empréstimos bancários', 'liability', 'credit', 2, false, true),
  ('332', 'Empréstimos por obrigações', 'liability', 'credit', 2, false, true),
  ('333', 'Empréstimos por títulos de participação', 'liability', 'credit', 2, false, true),
  ('339', 'Outros empréstimos obtidos', 'liability', 'credit', 2, false, true),
  ('34', 'ESTADO', 'liability', 'credit', 1, true, true),
  ('341', 'Imposto sobre os lucros', 'liability', 'credit', 2, false, true),
  ('342', 'Imposto de produção e consumo', 'liability', 'credit', 2, false, true),
  ('343', 'Imposto de rendimento de trabalho', 'liability', 'credit', 2, false, true),
  ('344', 'Imposto de circulação', 'liability', 'credit', 2, false, true),
  ('345', 'IVA', 'liability', 'credit', 2, true, true),
  ('3451', 'IVA dedutível', 'liability', 'debit', 3, false, true),
  ('3452', 'IVA liquidado', 'liability', 'credit', 3, false, true),
  ('346', 'Certificado de crédito fiscal a compensar', 'liability', 'credit', 2, false, true),
  ('348', 'Subsídios a preços', 'liability', 'credit', 2, false, true),
  ('349', 'Outros impostos', 'liability', 'credit', 2, false, true),
  ('35', 'ENTIDADES PARTICIPANTES E PARTICIPADAS', 'asset', 'debit', 1, true, true),
  ('351', 'Entidades participantes', 'asset', 'debit', 2, false, true),
  ('36', 'PESSOAL', 'liability', 'credit', 1, true, true),
  ('361', 'Pessoal - remunerações', 'liability', 'credit', 2, false, true),
  ('362', 'Pessoal - participação nos resultados', 'liability', 'credit', 2, false, true),
  ('363', 'Pessoal - adiantamentos', 'liability', 'credit', 2, false, true),
  ('369', 'Pessoal - outros', 'liability', 'credit', 2, false, true),
  ('37', 'OUTROS VALORES A RECEBER E A PAGAR', 'asset', 'debit', 1, true, true),
  ('371', 'Compra de imobilizado', 'asset', 'debit', 2, false, true),
  ('372', 'Vendas de imobilizado', 'asset', 'debit', 2, false, true),
  ('373', 'Proveitos a facturar', 'asset', 'debit', 2, false, true),
  ('374', 'Encargos a repartir por períodos futuros', 'asset', 'debit', 2, false, true),
  ('375', 'Encargos a pagar', 'asset', 'debit', 2, false, true),
  ('376', 'Proveitos a repartir por períodos futuros', 'asset', 'debit', 2, false, true),
  ('377', 'Contas transitórias', 'asset', 'debit', 2, false, true),
  ('379', 'Outros valores a receber e a pagar', 'asset', 'debit', 2, false, true),
  ('38', 'PROVISÕES PARA COBRANÇAS DUVIDOSAS', 'asset', 'credit', 1, true, true),
  ('381', 'Provisões para clientes', 'asset', 'credit', 2, false, true),
  ('382', 'Provisões para saldos devedores de fornecedores', 'asset', 'credit', 2, false, true),
  ('383', 'Provisões p/participantes e participadas', 'asset', 'credit', 2, false, true),
  ('384', 'Provisões p/dívidas do pessoal', 'asset', 'credit', 2, false, true),
  ('389', 'Provisões para outros saldos a receber', 'asset', 'credit', 2, false, true),
  ('39', 'PROVISÕES PARA OUTROS RISCOS E ENCARGOS', 'liability', 'credit', 1, true, true),
  ('391', 'Provisões para pensões', 'liability', 'credit', 2, false, true),
  ('392', 'Provisões para processos judiciais em curso', 'liability', 'credit', 2, false, true),
  ('393', 'Provisões para acidentes de trabalho', 'liability', 'credit', 2, false, true),
  ('394', 'Provisões para garantias dadas a clientes', 'liability', 'credit', 2, false, true),
  ('399', 'Provisões para outros riscos e encargos', 'liability', 'credit', 2, false, true),
  ('41', 'TÍTULOS NEGOCIÁVEIS', 'asset', 'debit', 1, true, true),
  ('411', 'Acções', 'asset', 'debit', 2, false, true),
  ('412', 'Obrigações', 'asset', 'debit', 2, false, true),
  ('413', 'Títulos da dívida pública', 'asset', 'debit', 2, false, true),
  ('42', 'DEPÓSITOS A PRAZO', 'asset', 'debit', 1, true, true),
  ('421', 'Moeda nacional', 'asset', 'debit', 2, false, true),
  ('422', 'Moeda estrangeira', 'asset', 'debit', 2, false, true),
  ('43', 'DEPÓSITOS À ORDEM', 'asset', 'debit', 1, true, true),
  ('431', 'Moeda nacional', 'asset', 'debit', 2, false, true),
  ('432', 'Moeda estrangeira', 'asset', 'debit', 2, false, true),
  ('44', 'OUTROS DEPÓSITOS', 'asset', 'debit', 1, true, true),
  ('441', 'Moeda nacional', 'asset', 'debit', 2, false, true),
  ('442', 'Moeda estrangeira', 'asset', 'debit', 2, false, true),
  ('45', 'CAIXA', 'asset', 'debit', 1, true, true),
  ('451', 'Fundo fixo', 'asset', 'debit', 2, false, true),
  ('452', 'Valores para depositar', 'asset', 'debit', 2, false, true),
  ('453', 'Valores destinados a pagamentos específicos', 'asset', 'debit', 2, false, true),
  ('51', 'CAPITAL', 'equity', 'credit', 1, true, true),
  ('52', 'ACÇÕES/QUOTAS PRÓPRIAS', 'equity', 'credit', 1, true, true),
  ('521', 'Valor nominal', 'equity', 'credit', 2, false, true),
  ('522', 'Descontos', 'equity', 'credit', 2, false, true),
  ('523', 'Prémios', 'equity', 'credit', 2, false, true),
  ('53', 'PRÉMIOS DE EMISSÃO', 'equity', 'credit', 1, true, true),
  ('54', 'PRESTAÇÕES SUPLEMENTARES', 'equity', 'credit', 1, true, true),
  ('55', 'RESERVAS LEGAIS', 'equity', 'credit', 1, true, true),
  ('56', 'RESERVAS DE REAVALIAÇÃO', 'equity', 'credit', 1, true, true),
  ('561', 'Legais', 'equity', 'credit', 2, false, true),
  ('562', 'Autónomas', 'equity', 'credit', 2, false, true),
  ('57', 'RESERVAS COM FINS ESPECIAIS', 'equity', 'credit', 1, true, true),
  ('58', 'RESERVAS LIVRES', 'equity', 'credit', 1, true, true),
  ('61', 'VENDAS', 'revenue', 'credit', 1, true, true),
  ('611', 'Produtos acabados e intermédios', 'revenue', 'credit', 2, false, true),
  ('612', 'Subprodutos, desperdícios, resíduos e refugos', 'revenue', 'credit', 2, false, true),
  ('613', 'Mercadorias', 'revenue', 'credit', 2, false, true),
  ('614', 'Embalagens de consumo', 'revenue', 'credit', 2, false, true),
  ('615', 'Subsídios a preços', 'revenue', 'credit', 2, false, true),
  ('617', 'Devoluções', 'revenue', 'credit', 2, false, true),
  ('618', 'Descontos e abatimentos', 'revenue', 'credit', 2, false, true),
  ('619', 'Transferência para resultados operacionais', 'revenue', 'credit', 2, false, true),
  ('62', 'PRESTAÇÕES DE SERVIÇOS', 'revenue', 'credit', 1, true, true),
  ('621', 'Serviços principais', 'revenue', 'credit', 2, false, true),
  ('622', 'Serviços secundários', 'revenue', 'credit', 2, false, true),
  ('628', 'Descontos e abatimentos', 'revenue', 'credit', 2, false, true),
  ('629', 'Transferência para resultados operacionais', 'revenue', 'credit', 2, false, true),
  ('63', 'OUTROS PROVEITOS OPERACIONAIS', 'revenue', 'credit', 1, true, true),
  ('631', 'Serviços suplementares', 'revenue', 'credit', 2, false, true),
  ('632', 'Royalties', 'revenue', 'credit', 2, false, true),
  ('633', 'Subsídios à exploração', 'revenue', 'credit', 2, false, true),
  ('634', 'Subsídios à investimento', 'revenue', 'credit', 2, false, true),
  ('635', 'IVA', 'revenue', 'credit', 2, false, true),
  ('638', 'Outros proveitos e ganhos operacionais', 'revenue', 'credit', 2, false, true),
  ('639', 'Transferência para resultados operacionais', 'revenue', 'credit', 2, false, true),
  ('64', 'VARIAÇÃO NOS INVENTÁRIOS DE PRODUTOS ACABADOS E DE PRODUÇÃO EM CURSO', 'revenue', 'credit', 1, true, true),
  ('641', 'Produtos e trabalhos em curso', 'revenue', 'credit', 2, false, true),
  ('642', 'Produtos acabados', 'revenue', 'credit', 2, false, true),
  ('643', 'Produtos intermédios', 'revenue', 'credit', 2, false, true),
  ('649', 'Transferência para resultados operacionais', 'revenue', 'credit', 2, false, true),
  ('65', 'TRABALHOS PARA A PRÓPRIA EMPRESA', 'revenue', 'credit', 1, true, true),
  ('651', 'Para imobilizado', 'revenue', 'credit', 2, false, true),
  ('652', 'Para encargos a repartir por exercícios futuros', 'revenue', 'credit', 2, false, true),
  ('659', 'Transferência para resultados operacionais', 'revenue', 'credit', 2, false, true),
  ('66', 'PROVEITOS E GANHOS FINANCEIROS GERAIS', 'revenue', 'credit', 1, true, true),
  ('661', 'Juros', 'revenue', 'credit', 2, false, true),
  ('662', 'Diferenças de câmbio favoráveis', 'revenue', 'credit', 2, false, true),
  ('663', 'Descontos de pronto pagamento obtidos', 'revenue', 'credit', 2, false, true),
  ('664', 'Rendimentos de investimentos em imóveis', 'revenue', 'credit', 2, false, true),
  ('665', 'Rendimento de participações de capital', 'revenue', 'credit', 2, false, true),
  ('666', 'Ganhos na alienação de aplicações financeiras', 'revenue', 'credit', 2, false, true),
  ('667', 'Redução de provisões', 'revenue', 'credit', 2, false, true),
  ('67', 'PROVEITOS E GANHOS FINANCEIROS EM SUBSIDIÁRIAS E ASSOCIADAS', 'revenue', 'credit', 1, true, true),
  ('671', 'Rendimento de participações de capital', 'revenue', 'credit', 2, false, true),
  ('679', 'Transferência para resultados em filiais e associadas', 'revenue', 'credit', 2, false, true),
  ('68', 'OUTROS PROVEITOS E GANHOS NÃO OPERACIONAIS', 'revenue', 'credit', 1, true, true),
  ('681', 'Redução de provisões', 'revenue', 'credit', 2, false, true),
  ('6810', 'Correcções relativas a exercícios anteriores', 'revenue', 'credit', 2, false, true),
  ('6811', 'Outros ganhos e perdas não operacionais', 'revenue', 'credit', 2, false, true),
  ('682', 'Anulação de amortizações extraordinárias', 'revenue', 'credit', 2, false, true),
  ('684', 'Ganhos em existências', 'revenue', 'credit', 2, false, true),
  ('685', 'Recuperação de dívidas', 'revenue', 'credit', 2, false, true),
  ('686', 'Benefícios de penalidades contratuais', 'revenue', 'credit', 2, false, true),
  ('688', 'Descontinuidade de operações', 'revenue', 'credit', 2, false, true),
  ('689', 'Alterações de políticas contabilísticas', 'revenue', 'credit', 2, false, true),
  ('69', 'PROVEITOS E GANHOS EXTRAORDINÁRIOS', 'revenue', 'credit', 1, true, true),
  ('691', 'Ganhos resultantes de catástrofes naturais', 'revenue', 'credit', 2, false, true),
  ('692', 'Ganhos resultantes de convulsões políticas', 'revenue', 'credit', 2, false, true),
  ('693', 'Ganhos resultantes de expropriações', 'revenue', 'credit', 2, false, true),
  ('694', 'Ganhos resultantes de sinistros', 'revenue', 'credit', 2, false, true),
  ('695', 'Subsídios', 'revenue', 'credit', 2, false, true),
  ('696', 'Anulação de passivos não exigível', 'revenue', 'credit', 2, false, true),
  ('699', 'Transferência para resultados extraordinários', 'revenue', 'credit', 2, false, true),
  ('71', 'CUSTO DAS EXISTÊNCIAS VENDIDAS', 'expense', 'debit', 1, true, true),
  ('711', 'Custo das mercadorias vendidas', 'expense', 'debit', 2, false, true),
  ('72', 'CUSTOS COM O PESSOAL', 'expense', 'debit', 1, true, true),
  ('721', 'Remunerações - Órgãos sociais', 'expense', 'debit', 2, false, true),
  ('722', 'Remunerações - Pessoal', 'expense', 'debit', 2, false, true),
  ('723', 'Pensões', 'expense', 'debit', 2, false, true),
  ('724', 'Prémios para pensões', 'expense', 'debit', 2, false, true),
  ('73', 'AMORTIZAÇÕES DO EXERCÍCIO', 'expense', 'debit', 1, true, true),
  ('731', 'Imobilizações corpóreas', 'expense', 'debit', 2, false, true),
  ('732', 'Imobilizações incorpóreas', 'expense', 'debit', 2, false, true),
  ('739', 'Transferência para resultados operacionais', 'expense', 'debit', 2, false, true),
  ('75', 'OUTROS CUSTOS E PERDAS OPERACIONAIS', 'expense', 'debit', 1, true, true),
  ('751', 'Subcontratos', 'expense', 'debit', 2, false, true),
  ('752', 'Fornecimentos e serviços de terceiros', 'expense', 'debit', 2, false, true),
  ('753', 'Impostos', 'expense', 'debit', 2, false, true),
  ('754', 'Despesas confidenciais', 'expense', 'debit', 2, false, true),
  ('755', 'Quotizações', 'expense', 'debit', 2, false, true),
  ('756', 'Ofertas e amostras de existências', 'expense', 'debit', 2, false, true),
  ('758', 'Outros custos e perdas operacionais', 'expense', 'debit', 2, false, true),
  ('759', 'Transferência para resultados operacionais', 'expense', 'debit', 2, false, true),
  ('76', 'CUSTOS E PERDAS FINANCEIROS GERAIS', 'expense', 'debit', 1, true, true),
  ('761', 'Juros', 'expense', 'debit', 2, false, true),
  ('762', 'Diferenças de câmbio desfavoráveis', 'expense', 'debit', 2, false, true),
  ('766', 'Perdas na alienação de aplicações financeiras', 'expense', 'debit', 2, false, true),
  ('767', 'Serviços bancários', 'expense', 'debit', 2, false, true),
  ('769', 'Transferência para resultados financeiros', 'expense', 'debit', 2, false, true),
  ('77', 'CUSTOS E PERDAS FINANCEIROS EM FILIAIS E ASSOCIADAS', 'expense', 'debit', 1, true, true),
  ('779', 'Transferência para resultados financeiros', 'expense', 'debit', 2, false, true),
  ('78', 'OUTROS CUSTOS E PERDAS NÃO OPERACIONAIS', 'expense', 'debit', 1, true, true),
  ('781', 'Provisões do exercício', 'expense', 'debit', 2, false, true),
  ('7810', 'Correcções relativas a exercícios anteriores', 'expense', 'debit', 2, false, true),
  ('7811', 'Outros custos e perdas não operacionais', 'expense', 'debit', 2, false, true),
  ('7819', 'Transferência para resultados não operacionais', 'expense', 'debit', 2, false, true),
  ('782', 'Amortizações extraordinárias', 'expense', 'debit', 2, false, true),
  ('783', 'Perdas em imobilizações', 'expense', 'debit', 2, false, true),
  ('784', 'Perdas em existências', 'expense', 'debit', 2, false, true),
  ('785', 'Dívidas incobráveis', 'expense', 'debit', 2, false, true),
  ('786', 'Multas e penalidades contratuais', 'expense', 'debit', 2, false, true),
  ('787', 'Custo de reestruturação', 'expense', 'debit', 2, false, true),
  ('788', 'Descontinuidade de operações', 'expense', 'debit', 2, false, true),
  ('789', 'Alterações de políticas contabilísticas', 'expense', 'debit', 2, false, true),
  ('79', 'CUSTOS E PERDAS EXTRAORDINÁRIOS', 'expense', 'debit', 1, true, true),
  ('791', 'Perdas resultantes de catástrofes naturais', 'expense', 'debit', 2, false, true),
  ('792', 'Perdas resultantes de convulsões políticas', 'expense', 'debit', 2, false, true),
  ('793', 'Perdas resultantes de expropriações', 'expense', 'debit', 2, false, true),
  ('794', 'Perdas resultantes de sinistros', 'expense', 'debit', 2, false, true),
  ('799', 'Transferência para resultados extraordinários', 'expense', 'debit', 2, false, true),
  ('81', 'RESULTADOS TRANSITADOS', 'equity', 'credit', 1, true, true),
  ('811', 'Ano', 'equity', 'credit', 2, false, true),
  ('812', 'Ano', 'equity', 'credit', 2, false, true),
  ('82', 'RESULTADOS OPERACIONAIS', 'equity', 'credit', 1, true, true),
  ('821', 'Vendas', 'equity', 'credit', 2, false, true),
  ('8219', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('822', 'Prestações de serviços', 'equity', 'credit', 2, false, true),
  ('823', 'Outros proveitos operacionais', 'equity', 'credit', 2, false, true),
  ('824', 'Variação nos inventários de produtos acabados e produtos em vias de fabrico', 'equity', 'credit', 2, false, true),
  ('825', 'Trabalhos para a própria empresa', 'equity', 'credit', 2, false, true),
  ('826', 'Custo das mercadorias vendidas e das matérias consumidas', 'equity', 'credit', 2, false, true),
  ('827', 'Custos com o pessoal', 'equity', 'credit', 2, false, true),
  ('828', 'Amortizações do exercício', 'equity', 'credit', 2, false, true),
  ('829', 'Outros custos operacionais', 'equity', 'credit', 2, false, true),
  ('83', 'RESULTADOS FINANCEIROS', 'equity', 'credit', 1, true, true),
  ('831', 'Proveitos e ganhos financeiros gerais', 'equity', 'credit', 2, false, true),
  ('832', 'Custos e perdas financeiros gerais', 'equity', 'credit', 2, false, true),
  ('839', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('84', 'RESULTADOS FINANCEIROS EM FILIAIS E ASSOCIADAS', 'equity', 'credit', 1, true, true),
  ('841', 'Proveitos e ganhos em filiais e associadas', 'equity', 'credit', 2, false, true),
  ('842', 'Custos e perdas em filiais e associadas', 'equity', 'credit', 2, false, true),
  ('849', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('85', 'RESULTADOS NÃO OPERACIONAIS', 'equity', 'credit', 1, true, true),
  ('851', 'Proveitos e ganhos não operacionais', 'equity', 'credit', 2, false, true),
  ('852', 'Custos e perdas não operacionais', 'equity', 'credit', 2, false, true),
  ('859', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('86', 'RESULTADOS EXTRAORDINÁRIOS', 'equity', 'credit', 1, true, true),
  ('861', 'Proveitos e ganhos extraordinários', 'equity', 'credit', 2, false, true),
  ('862', 'Custos e perdas extraordinários', 'equity', 'credit', 2, false, true),
  ('869', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('87', 'IMPOSTOS SOBRE OS LUCROS', 'equity', 'credit', 1, true, true),
  ('871', 'Imposto sobre os resultados correntes', 'equity', 'credit', 2, false, true),
  ('872', 'Imposto sobre os resultados extraordinários', 'equity', 'credit', 2, false, true),
  ('879', 'Transferência para resultados líquidos', 'equity', 'credit', 2, false, true),
  ('88', 'RESULTADO LÍQUIDO DO EXERCÍCIO', 'equity', 'credit', 1, true, true),
  ('881', 'Resultados operacionais', 'equity', 'credit', 2, false, true),
  ('882', 'Resultados financeiros gerais', 'equity', 'credit', 2, false, true),
  ('883', 'Resultados em filiais e associadas', 'equity', 'credit', 2, false, true),
  ('884', 'Resultados não operacionais', 'equity', 'credit', 2, false, true),
  ('885', 'Imposto sobre os resultados correntes', 'equity', 'credit', 2, false, true),
  ('886', 'Resultados extraordinários', 'equity', 'credit', 2, false, true),
  ('887', 'Imposto sobre os resultados extraordinários', 'equity', 'credit', 2, false, true),
  ('889', 'Transferência para resultados transitados', 'equity', 'credit', 2, false, true),
  ('89', 'DIVIDENDOS ANTECIPADOS', 'equity', 'credit', 1, true, true),
  ('899', 'Transferência para resultados transitados', 'equity', 'credit', 2, false, true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  account_type = EXCLUDED.account_type,
  account_nature = EXCLUDED.account_nature,
  level = EXCLUDED.level,
  is_header = EXCLUDED.is_header,
  is_active = true;

-- 3) Wire parent_id from the (code, parent_code) map.
UPDATE chart_of_accounts c
SET parent_id = p.id
FROM (VALUES
  ('111', '11'),
  ('112', '11'),
  ('113', '11'),
  ('114', '11'),
  ('115', '11'),
  ('116', '11'),
  ('119', '11'),
  ('121', '12'),
  ('122', '12'),
  ('123', '12'),
  ('124', '12'),
  ('129', '12'),
  ('131', '13'),
  ('132', '13'),
  ('133', '13'),
  ('134', '13'),
  ('135', '13'),
  ('139', '13'),
  ('141', '14'),
  ('142', '14'),
  ('147', '14'),
  ('148', '14'),
  ('149', '14'),
  ('181', '18'),
  ('182', '18'),
  ('183', '18'),
  ('191', '19'),
  ('192', '19'),
  ('211', '21'),
  ('212', '21'),
  ('217', '21'),
  ('218', '21'),
  ('251', '25'),
  ('252', '25'),
  ('261', '26'),
  ('281', '28'),
  ('282', '28'),
  ('292', '29'),
  ('293', '29'),
  ('294', '29'),
  ('295', '29'),
  ('296', '29'),
  ('311', '31'),
  ('312', '31'),
  ('313', '31'),
  ('318', '31'),
  ('319', '31'),
  ('321', '32'),
  ('322', '32'),
  ('328', '32'),
  ('329', '32'),
  ('331', '33'),
  ('332', '33'),
  ('333', '33'),
  ('339', '33'),
  ('341', '34'),
  ('342', '34'),
  ('343', '34'),
  ('344', '34'),
  ('345', '34'),
  ('3451', '345'),
  ('3452', '345'),
  ('346', '34'),
  ('348', '34'),
  ('349', '34'),
  ('351', '35'),
  ('361', '36'),
  ('362', '36'),
  ('363', '36'),
  ('369', '36'),
  ('371', '37'),
  ('372', '37'),
  ('373', '37'),
  ('374', '37'),
  ('375', '37'),
  ('376', '37'),
  ('377', '37'),
  ('379', '37'),
  ('381', '38'),
  ('382', '38'),
  ('383', '38'),
  ('384', '38'),
  ('389', '38'),
  ('391', '39'),
  ('392', '39'),
  ('393', '39'),
  ('394', '39'),
  ('399', '39'),
  ('411', '41'),
  ('412', '41'),
  ('413', '41'),
  ('421', '42'),
  ('422', '42'),
  ('431', '43'),
  ('432', '43'),
  ('441', '44'),
  ('442', '44'),
  ('451', '45'),
  ('452', '45'),
  ('453', '45'),
  ('521', '52'),
  ('522', '52'),
  ('523', '52'),
  ('561', '56'),
  ('562', '56'),
  ('611', '61'),
  ('612', '61'),
  ('613', '61'),
  ('614', '61'),
  ('615', '61'),
  ('617', '61'),
  ('618', '61'),
  ('619', '61'),
  ('621', '62'),
  ('622', '62'),
  ('628', '62'),
  ('629', '62'),
  ('631', '63'),
  ('632', '63'),
  ('633', '63'),
  ('634', '63'),
  ('635', '63'),
  ('638', '63'),
  ('639', '63'),
  ('641', '64'),
  ('642', '64'),
  ('643', '64'),
  ('649', '64'),
  ('651', '65'),
  ('652', '65'),
  ('659', '65'),
  ('661', '66'),
  ('662', '66'),
  ('663', '66'),
  ('664', '66'),
  ('665', '66'),
  ('666', '66'),
  ('667', '66'),
  ('671', '67'),
  ('679', '67'),
  ('681', '68'),
  ('6810', '68'),
  ('6811', '68'),
  ('682', '68'),
  ('684', '68'),
  ('685', '68'),
  ('686', '68'),
  ('688', '68'),
  ('689', '68'),
  ('691', '69'),
  ('692', '69'),
  ('693', '69'),
  ('694', '69'),
  ('695', '69'),
  ('696', '69'),
  ('699', '69'),
  ('711', '71'),
  ('721', '72'),
  ('722', '72'),
  ('723', '72'),
  ('724', '72'),
  ('731', '73'),
  ('732', '73'),
  ('739', '73'),
  ('751', '75'),
  ('752', '75'),
  ('753', '75'),
  ('754', '75'),
  ('755', '75'),
  ('756', '75'),
  ('758', '75'),
  ('759', '75'),
  ('761', '76'),
  ('762', '76'),
  ('766', '76'),
  ('767', '76'),
  ('769', '76'),
  ('779', '77'),
  ('781', '78'),
  ('7810', '78'),
  ('7811', '78'),
  ('7819', '78'),
  ('782', '78'),
  ('783', '78'),
  ('784', '78'),
  ('785', '78'),
  ('786', '78'),
  ('787', '78'),
  ('788', '78'),
  ('789', '78'),
  ('791', '79'),
  ('792', '79'),
  ('793', '79'),
  ('794', '79'),
  ('799', '79'),
  ('811', '81'),
  ('812', '81'),
  ('821', '82'),
  ('8219', '82'),
  ('822', '82'),
  ('823', '82'),
  ('824', '82'),
  ('825', '82'),
  ('826', '82'),
  ('827', '82'),
  ('828', '82'),
  ('829', '82'),
  ('831', '83'),
  ('832', '83'),
  ('839', '83'),
  ('841', '84'),
  ('842', '84'),
  ('849', '84'),
  ('851', '85'),
  ('852', '85'),
  ('859', '85'),
  ('861', '86'),
  ('862', '86'),
  ('869', '86'),
  ('871', '87'),
  ('872', '87'),
  ('879', '87'),
  ('881', '88'),
  ('882', '88'),
  ('883', '88'),
  ('884', '88'),
  ('885', '88'),
  ('886', '88'),
  ('887', '88'),
  ('889', '88'),
  ('899', '89')
) AS m(code, parent_code)
JOIN chart_of_accounts p ON p.code = m.parent_code
WHERE c.code = m.code;

-- 4) Recompute children_count.
UPDATE chart_of_accounts
SET children_count = (
  SELECT COUNT(*) FROM chart_of_accounts child
  WHERE child.parent_id = chart_of_accounts.id AND child.is_active = true
);

-- 5) Best-effort cleanup of leftover deactivated accounts that carry no journal lines.
DELETE FROM chart_of_accounts
WHERE is_active = false
  AND id NOT IN (SELECT account_id FROM journal_entry_lines)
  AND id NOT IN (SELECT parent_id FROM chart_of_accounts WHERE parent_id IS NOT NULL);
