// Products API routes — with Optimistic Locking (Phase 3) + Multi-Price Levels
const crypto = require('crypto');
const express = require('express');
const db = require('../db');
const { DEFAULT_VAT_RATE } = require('../taxDefaults');
const { checkOptimisticLock } = require('../middleware/security');
const { attachUserBranchScope, resolveListBranchId } = require('../middleware/branchScope');

function sanitizeUuid(value) {
  if (typeof value !== 'string') return value ?? null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(trimmed) ? trimmed : null;
}

/** Preserve text branch ids (e.g. branch-main) on SQLite; UUID on Postgres when valid. */
function resolveProductBranchId(req, requestedBranchId) {
  const scoped = resolveListBranchId(req, requestedBranchId);
  if (scoped === undefined) return undefined;
  if (!scoped) return null;
  const key = String(scoped).trim();
  if (db.engine === 'sqlite') return key;
  return sanitizeUuid(key) || key;
}

function normalizeSkuKey(sku) {
  return String(sku || '').trim().toLowerCase();
}

async function loadMainBranchIds() {
  const result = await db.query(
    `SELECT id FROM branches WHERE COALESCE(is_main, 0) != 0 AND COALESCE(is_active, 1) != 0`,
  );
  return result.rows.map((row) => String(row.id).trim()).filter(Boolean);
}

function isCatalogBranchScope(branchId, mainBranchIds) {
  if (branchId == null || String(branchId).trim() === '') return true;
  return mainBranchIds.includes(String(branchId).trim());
}

function normalizeCatalogBranchKey(branchId, mainBranchIds = []) {
  const value = String(branchId ?? '').trim();
  if (!value) return 'catalog';
  if (mainBranchIds.includes(value)) return 'catalog';
  return value;
}

function normalizeNameKey(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ');
}

function skuLooksAutoGenerated(sku) {
  const value = String(sku || '').trim();
  if (!value) return true;
  return /^AUTO-/i.test(value) || /^SKU-\d{10,}/i.test(value);
}

function rowDisplayScore(row, branchId, mainBranchIds = []) {
  let score = Number(row.stock || 0) * 1000;
  if (branchId && String(row.branch_id || '') === String(branchId)) score += 1_000_000;
  if (normalizeCatalogBranchKey(row.branch_id, mainBranchIds) === 'catalog' && !String(row.branch_id || '').trim()) {
    score += 500;
  }
  if (String(row.branch_id || '').trim()) score += 100;
  if (!skuLooksAutoGenerated(row.sku)) score += 50;
  if (String(row.barcode || '').trim()) score += 25;
  return score;
}

function shouldMergeProductDuplicates(a, b, mainBranchIds = []) {
  const nameA = normalizeNameKey(a.name);
  const nameB = normalizeNameKey(b.name);
  if (!nameA || nameA !== nameB) return false;
  const branchA = normalizeCatalogBranchKey(a.branch_id, mainBranchIds);
  const branchB = normalizeCatalogBranchKey(b.branch_id, mainBranchIds);
  if (branchA !== branchB) return false;
  const skuA = normalizeSkuKey(a.sku);
  const skuB = normalizeSkuKey(b.sku);
  if (skuA && skuB && skuA === skuB) return true;
  const barcodeA = String(a.barcode || '').trim().toLowerCase();
  const barcodeB = String(b.barcode || '').trim().toLowerCase();
  if (barcodeA && barcodeB && barcodeA === barcodeB) return true;
  if (skuLooksAutoGenerated(a.sku) || skuLooksAutoGenerated(b.sku)) return true;
  return true;
}

function dedupeRowKey(row, mainBranchIds = []) {
  const scope = normalizeCatalogBranchKey(row.branch_id, mainBranchIds);
  const skuKey = normalizeSkuKey(row.sku);
  if (skuKey && !skuLooksAutoGenerated(row.sku)) {
    return `${scope}|sku:${skuKey}`;
  }
  const nameKey = normalizeNameKey(row.name);
  return `${scope}|name:${nameKey || row.id}`;
}

/** Catalog/sede rows: store branch_id as NULL so UNIQUE(sku, branch_id) does not allow NULL + main duplicates. */
async function normalizeStoredBranchId(branchId, mainBranchIds = null) {
  const ids = mainBranchIds || (await loadMainBranchIds());
  const key = branchId == null ? '' : String(branchId).trim();
  if (!key) return null;
  if (ids.includes(key)) return null;
  return key;
}

async function findExistingProductForUpsert({ sku, name, branchId }) {
  const skuTrim = String(sku || '').trim();
  const nameTrim = String(name || '').trim();
  const storedBranchId = await normalizeStoredBranchId(branchId);

  if (skuTrim) {
    const bySku = await findExistingProductBySku(skuTrim, storedBranchId ?? branchId);
    if (bySku) return { id: bySku, matchedBy: 'sku' };
  }

  if (nameTrim) {
    const byName = await findExistingProductByName(nameTrim, storedBranchId ?? branchId);
    if (byName?.id) return { id: byName.id, matchedBy: 'name', existingSku: byName.sku };
  }

  return null;
}

/** One row per SKU when duplicate branch/catalog rows exist (e.g. after repeated transfers). */
function dedupeProductsBySku(rows, branchId, mainBranchIds = []) {
  const bySku = new Map();
  for (const row of rows) {
    const key = dedupeRowKey(row, mainBranchIds);
    const prev = bySku.get(key);
    if (!prev) {
      bySku.set(key, row);
      continue;
    }
    const pick = rowDisplayScore(row, branchId, mainBranchIds) >= rowDisplayScore(prev, branchId, mainBranchIds) ? row : prev;
    const other = pick === row ? prev : row;
    bySku.set(key, {
      ...pick,
      supplier_id: pick.supplier_id || other.supplier_id || null,
      supplier_name: pick.supplier_name || other.supplier_name || null,
    });
  }

  const merged = [];
  for (const row of bySku.values()) {
    const index = merged.findIndex((existing) => shouldMergeProductDuplicates(existing, row, mainBranchIds));
    if (index < 0) {
      merged.push(row);
      continue;
    }
    const prev = merged[index];
    const pick = rowDisplayScore(row, branchId, mainBranchIds) >= rowDisplayScore(prev, branchId, mainBranchIds) ? row : prev;
    const other = pick === row ? prev : row;
    merged[index] = {
      ...pick,
      supplier_id: pick.supplier_id || other.supplier_id || null,
      supplier_name: pick.supplier_name || other.supplier_name || null,
    };
  }
  return merged;
}

async function findExistingProductBySku(skuTrim, resolvedBranchId) {
  const mainBranchIds = await loadMainBranchIds();
  if (isCatalogBranchScope(resolvedBranchId, mainBranchIds)) {
    const params = [skuTrim];
    let sql = `
      SELECT id FROM products
      WHERE COALESCE(is_active, 1) != 0
        AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($1)
        AND (
          branch_id IS NULL
          OR TRIM(COALESCE(branch_id, '')) = ''`;
    for (const id of mainBranchIds) {
      params.push(id);
      sql += ` OR branch_id = $${params.length}`;
    }
    sql += `
        )
      ORDER BY CASE WHEN branch_id IS NULL OR TRIM(COALESCE(branch_id, '')) = '' THEN 0 ELSE 1 END,
               created_at ASC
      LIMIT 1`;
    const result = await db.query(sql, params);
    return result.rows[0]?.id || null;
  }

  const result = await db.query(
    `SELECT id FROM products
     WHERE COALESCE(is_active, 1) != 0
       AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($1)
       AND branch_id = $2
     ORDER BY created_at ASC
     LIMIT 1`,
    [skuTrim, resolvedBranchId],
  );
  return result.rows[0]?.id || null;
}

async function findExistingProductByName(nameTrim, resolvedBranchId) {
  const mainBranchIds = await loadMainBranchIds();
  if (isCatalogBranchScope(resolvedBranchId, mainBranchIds)) {
    const params = [nameTrim];
    let sql = `
      SELECT id, sku FROM products
      WHERE COALESCE(is_active, 1) != 0
        AND LOWER(TRIM(COALESCE(name, ''))) = LOWER($1)
        AND (
          branch_id IS NULL
          OR TRIM(COALESCE(branch_id, '')) = ''`;
    for (const id of mainBranchIds) {
      params.push(id);
      sql += ` OR branch_id = $${params.length}`;
    }
    sql += `
        )
      ORDER BY CASE WHEN branch_id IS NULL OR TRIM(COALESCE(branch_id, '')) = '' THEN 0 ELSE 1 END,
               created_at ASC
      LIMIT 1`;
    const result = await db.query(sql, params);
    return result.rows[0] || null;
  }

  const result = await db.query(
    `SELECT id, sku FROM products
     WHERE COALESCE(is_active, 1) != 0
       AND LOWER(TRIM(COALESCE(name, ''))) = LOWER($1)
       AND branch_id = $2
     ORDER BY created_at ASC
     LIMIT 1`,
    [nameTrim, resolvedBranchId],
  );
  return result.rows[0] || null;
}

module.exports = function(broadcastTable) {
  const router = express.Router();
  router.use(attachUserBranchScope);

  // Get all products
  router.get('/', async (req, res) => {
    try {
      const branchId = resolveListBranchId(req, req.query.branchId);
      if (branchId === undefined) {
        return res.json([]);
      }
      const params = [];
      let query;

      if (branchId) {
        const branchKey = String(branchId).trim();
        // One row per catalog SKU; stock from branch row + movements at this warehouse (by SKU).
        query = `
          SELECT
            COALESCE(bp.id, p.id) AS id,
            COALESCE(bp.name, p.name) AS name,
            COALESCE(bp.sku, p.sku) AS sku,
            COALESCE(bp.barcode, p.barcode) AS barcode,
            COALESCE(bp.category, p.category) AS category,
            COALESCE(bp.price, p.price) AS price,
            COALESCE(bp.price2, p.price2) AS price2,
            COALESCE(bp.price3, p.price3) AS price3,
            COALESCE(bp.price4, p.price4) AS price4,
            COALESCE(bp.cost, p.cost) AS cost,
            COALESCE(bp.first_cost, p.first_cost, bp.cost, p.cost) AS first_cost,
            COALESCE(bp.last_cost, p.last_cost, bp.cost, p.cost) AS last_cost,
            COALESCE(bp.avg_cost, p.avg_cost, bp.cost, p.cost) AS avg_cost,
            CASE
              WHEN p.sku IS NOT NULL AND TRIM(p.sku) != '' AND EXISTS (
                SELECT 1
                FROM stock_movements sm
                INNER JOIN products pm ON pm.id = sm.product_id
                WHERE sm.warehouse_id = $1
                  AND LOWER(TRIM(COALESCE(pm.sku, ''))) = LOWER(TRIM(p.sku))
              ) THEN MAX(0, COALESCE((
                SELECT SUM(
                  CASE
                    WHEN sm.movement_type = 'IN' THEN sm.quantity
                    WHEN sm.movement_type = 'OUT' THEN -sm.quantity
                    ELSE 0
                  END
                )
                FROM stock_movements sm
                INNER JOIN products pm ON pm.id = sm.product_id
                WHERE sm.warehouse_id = $1
                  AND LOWER(TRIM(COALESCE(pm.sku, ''))) = LOWER(TRIM(p.sku))
              ), 0))
              WHEN bp.id IS NOT NULL THEN COALESCE(bp.stock, 0)
              WHEN p.branch_id = $1 THEN COALESCE(p.stock, 0)
              ELSE 0
            END AS stock,
            COALESCE(bp.unit, p.unit) AS unit,
            COALESCE(bp.tax_rate, p.tax_rate) AS tax_rate,
            COALESCE(bp.branch_id, $1) AS branch_id,
            COALESCE(bp.supplier_id, p.supplier_id) AS supplier_id,
            COALESCE(bp.supplier_name, p.supplier_name) AS supplier_name,
            COALESCE(bp.is_active, p.is_active) AS is_active,
            COALESCE(bp.created_at, p.created_at) AS created_at,
            COALESCE(bp.updated_at, p.updated_at) AS updated_at
          FROM products p
          LEFT JOIN products bp ON bp.id = (
            SELECT bx.id
            FROM products bx
            WHERE COALESCE(bx.is_active, 1) != 0
              AND bx.branch_id = $1
              AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
              AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
            ORDER BY bx.updated_at DESC, bx.created_at DESC
            LIMIT 1
          )
          WHERE COALESCE(p.is_active, 1) != 0
            AND (
              p.branch_id = $1
              OR bp.id IS NOT NULL
              OR (
                (p.branch_id IS NULL OR TRIM(COALESCE(p.branch_id, '')) = '')
                AND NOT EXISTS (
                  SELECT 1 FROM products bx
                  WHERE COALESCE(bx.is_active, 1) != 0 AND bx.branch_id = $1
                    AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
                    AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
                )
              )
              OR (
                p.branch_id IN (
                  SELECT id FROM branches
                  WHERE COALESCE(is_main, 0) != 0 AND COALESCE(is_active, 1) != 0
                )
                AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
                AND NOT EXISTS (
                  SELECT 1 FROM products bx
                  WHERE COALESCE(bx.is_active, 1) != 0 AND bx.branch_id = $1
                    AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
                )
              )
              OR EXISTS (
                SELECT 1
                FROM stock_movements sm
                WHERE sm.warehouse_id = $1
                  AND sm.product_id = p.id
              )
            )
          ORDER BY name`;
        params.push(branchKey);
      } else {
        query = `
          SELECT p.*,
            COALESCE(p.first_cost, p.cost) AS first_cost,
            COALESCE(p.last_cost, p.cost) AS last_cost,
            COALESCE(p.avg_cost, p.cost) AS avg_cost,
            p.stock AS stock
          FROM products p
          WHERE COALESCE(p.is_active, 1) != 0
          ORDER BY p.name`;
      }

      const result = await db.query(query, params);
      const mainBranchIds = await loadMainBranchIds();
      const rows = dedupeProductsBySku(
        result.rows,
        branchId ? String(branchId).trim() : undefined,
        mainBranchIds,
      );
      console.log(`[PRODUCTS GET] branchId=${branchId || 'ALL'} rows=${rows.length}`);
      if (rows.length > 0) {
        console.log('[PRODUCTS GET] first_rows=', JSON.stringify(rows.slice(0, 5)));
      }
      res.json(rows);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to fetch products' });
    }
  });

  /** Fill supplier from another row with the same SKU when this row has none. */
  async function enrichProductSupplierFromSku(row) {
    if (!row) return row;
    const hasId = row.supplier_id != null && String(row.supplier_id).trim() !== '';
    const hasName = row.supplier_name != null && String(row.supplier_name).trim() !== '';
    if ((hasId || hasName) || !row.sku || !String(row.sku).trim()) return row;

    const sibling = await db.query(
      `SELECT supplier_id, supplier_name
       FROM products
       WHERE LOWER(TRIM(COALESCE(sku, ''))) = LOWER(TRIM($1))
         AND (
           (supplier_id IS NOT NULL AND TRIM(COALESCE(supplier_id, '')) != '')
           OR (supplier_name IS NOT NULL AND TRIM(COALESCE(supplier_name, '')) != '')
         )
       ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST
       LIMIT 1`,
      [row.sku],
    );
    const src = sibling.rows[0];
    if (!src) return row;
    return {
      ...row,
      supplier_id: row.supplier_id || src.supplier_id || null,
      supplier_name: row.supplier_name || src.supplier_name || null,
    };
  }

  // Get single product (supplier resolved from sibling SKU rows when missing)
  router.get('/:id', async (req, res) => {
    try {
      const { id } = req.params;
      const result = await db.query('SELECT * FROM products WHERE id = $1', [id]);
      if (!result.rows[0]) {
        return res.status(404).json({ error: 'Product not found' });
      }
      const row = await enrichProductSupplierFromSku(result.rows[0]);
      res.json(row);
    } catch (error) {
      console.error('[PRODUCTS GET/:id ERROR]', error);
      res.status(500).json({ error: 'Failed to fetch product' });
    }
  });

  // Create product
  router.post('/', async (req, res) => {
    try {
      const { name, sku, barcode, category, price, price2, price3, price4, cost, stock, unit, taxRate, branchId, isActive, supplierId, supplierName } = req.body;
      const activeInt = isActive !== false ? 1 : 0;

      const c = Number(cost) || 0;
      const resolvedBranchId = resolveProductBranchId(req, branchId);
      if (resolvedBranchId === undefined) {
        return res.status(403).json({ error: 'Sem filial atribuída para criar produtos.' });
      }

      const skuTrim = String(sku || '').trim();
      if (!skuTrim) {
        return res.status(400).json({ error: 'Código (SKU) é obrigatório.' });
      }

      const storedBranchId = await normalizeStoredBranchId(resolvedBranchId);
      const existing = await findExistingProductForUpsert({
        sku: skuTrim,
        name: String(name || '').trim(),
        branchId: resolvedBranchId,
      });

      if (existing?.id) {
        const canonicalSku =
          existing.matchedBy === 'name'
          && existing.existingSku
          && String(existing.existingSku).trim()
          && !skuLooksAutoGenerated(existing.existingSku)
            ? String(existing.existingSku).trim()
            : skuTrim;
        const result = await db.query(
          `UPDATE products
           SET name = $1, sku = $2, barcode = $3, category = $4, price = $5, price2 = $6, price3 = $7, price4 = $8,
               cost = $9, stock = COALESCE($10, stock), unit = $11, tax_rate = $12, is_active = $13,
               branch_id = $14,
               supplier_id = $15, supplier_name = $16,
               last_cost = COALESCE($9, last_cost), avg_cost = COALESCE($9, avg_cost),
               updated_at = CURRENT_TIMESTAMP
           WHERE id = $17
           RETURNING *`,
          [
            name, canonicalSku, barcode, category, price, price2 || 0, price3 || 0, price4 || 0,
            c, stock ?? null, unit || 'un', taxRate ?? DEFAULT_VAT_RATE, activeInt,
            storedBranchId,
            sanitizeUuid(supplierId), supplierName || null,
            existing.id,
          ],
        );
        await broadcastTable('products');
        return res.status(200).json(result.rows[0]);
      }

      const id = crypto.randomUUID();
      // SQLite expands $10 four times from ONE param — do not pass c,c,c,c in the array.
      const result = await db.query(
        `INSERT INTO products (id, name, sku, barcode, category, price, price2, price3, price4, cost, first_cost, last_cost, avg_cost, stock, unit, tax_rate, branch_id, is_active, supplier_id, supplier_name)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, $10, $10, $11, $12, $13, $14, $15, $16, $17)
         RETURNING *`,
        [
          id, name, skuTrim, barcode, category, price, price2 || 0, price3 || 0, price4 || 0,
          c,
          stock || 0, unit || 'un', taxRate ?? DEFAULT_VAT_RATE, storedBranchId, activeInt,
          sanitizeUuid(supplierId), supplierName || null,
        ]
      );
      
      await broadcastTable('products');
      res.status(201).json(result.rows[0]);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      const msg = String(error?.message || '');
      if (/unique|duplicate|UNIQUE constraint/i.test(msg)) {
        return res.status(409).json({
          error: 'Já existe um produto com este código (SKU) nesta filial ou catálogo partilhado.',
        });
      }
      res.status(500).json({ error: 'Failed to create product' });
    }
  });

  // Update product (with optimistic locking)
  router.put('/:id', async (req, res) => {
    try {
      const { id } = req.params;
      const { name, sku, barcode, category, price, price2, price3, price4, cost, stock, unit, taxRate, branchId, isActive, version, supplierId, supplierName, lastCost, avgCost } = req.body;
      
      let result;
      if (version != null) {
        result = await db.query(
          `UPDATE products 
           SET name=$1, sku=$2, barcode=$3, category=$4, price=$5, cost=$6, 
               stock=$7, unit=$8, tax_rate=$9, branch_id=$10, is_active=$11,
               price2=$12, price3=$13, price4=$14,
               supplier_id=$15, supplier_name=$16,
               last_cost=COALESCE($17, last_cost), avg_cost=COALESCE($18, avg_cost),
               version = version + 1
           WHERE id=$19 AND version=$20
           RETURNING *`,
          [name, sku, barcode, category, price, cost, stock, unit, taxRate,
           resolveProductBranchId(req, branchId) ?? sanitizeUuid(branchId),
           isActive !== false ? 1 : 0,
           price2 || 0, price3 || 0, price4 || 0,
           sanitizeUuid(supplierId), supplierName || null,
           lastCost ?? null, avgCost ?? null,
           id, version]
        );
        if (!checkOptimisticLock(result, res, 'Product')) return;
      } else {
        result = await db.query(
          `UPDATE products 
           SET name=$1, sku=$2, barcode=$3, category=$4, price=$5, cost=$6, 
               stock=$7, unit=$8, tax_rate=$9, branch_id=$10, is_active=$11,
               price2=$12, price3=$13, price4=$14,
               supplier_id=$15, supplier_name=$16,
               last_cost=COALESCE($17, last_cost), avg_cost=COALESCE($18, avg_cost)
           WHERE id=$19
           RETURNING *`,
          [name, sku, barcode, category, price, cost, stock, unit, taxRate,
           resolveProductBranchId(req, branchId) ?? sanitizeUuid(branchId),
           isActive !== false ? 1 : 0,
           price2 || 0, price3 || 0, price4 || 0,
           sanitizeUuid(supplierId), supplierName || null,
           lastCost ?? null, avgCost ?? null,
           id]
        );
        if (result.rowCount === 0) {
          return res.status(404).json({ error: 'Product not found' });
        }
      }
      
      const updated = result.rows[0];
      const skuKey = String(updated?.sku || '').trim();
      if (skuKey && taxRate != null && taxRate !== '') {
        await db.query(
          `UPDATE products
           SET tax_rate = $1, updated_at = CURRENT_TIMESTAMP
           WHERE COALESCE(is_active, 1) != 0
             AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($2)`,
          [Number(taxRate), skuKey]
        );
      }

      await broadcastTable('products');
      res.json(updated);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to update product' });
    }
  });

  // Update stock
  router.patch('/:id/stock', async (req, res) => {
    try {
      const { id } = req.params;
      const { quantityChange } = req.body;
      
      const result = await db.query(
        'UPDATE products SET stock = stock + $1 WHERE id = $2 RETURNING *',
        [quantityChange, id]
      );
      
      await broadcastTable('products');
      res.json(result.rows[0]);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to update stock' });
    }
  });

  // Batch import products (SQLite + PostgreSQL)
  router.post('/batch', async (req, res) => {
    try {
      const { products: productList } = req.body;
      if (!Array.isArray(productList) || productList.length === 0) {
        return res.status(400).json({ error: 'products array is required' });
      }

      let inserted = 0;
      let updated = 0;
      let failed = 0;
      const errors = [];

      for (const p of productList) {
        const rawSku = String(p?.sku ?? p?.codigo ?? p?.code ?? '').trim();
        const rawName = String(p?.name ?? p?.descricao ?? p?.description ?? p?.designacao ?? '').trim();
        const branchId = resolveProductBranchId(req, p.branchId);
        if (branchId === undefined) {
          failed += 1;
          errors.push({ sku: rawSku || rawName || '?', error: 'Sem filial atribuída' });
          continue;
        }
        const cost = Number(p.cost) || 0;
        const stock = Number(p.stock ?? p.quantidade) || 0;
        const activeInt = p.isActive !== false ? 1 : 0;

        let sku = rawSku;
        let existingId = null;
        let existingMatch = null;

        if (sku || rawName) {
          existingMatch = await findExistingProductForUpsert({
            sku: rawSku,
            name: rawName,
            branchId,
          });
        }

        if (existingMatch?.id) {
          existingId = existingMatch.id;
          if (existingMatch.existingSku && String(existingMatch.existingSku).trim()) {
            sku = String(existingMatch.existingSku).trim();
          } else if (!sku) {
            sku = rawName;
          }
        } else if (!sku && rawName) {
          sku = `AUTO-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        }

        if (!sku) {
          sku = `AUTO-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        }
        const name = rawName || sku;
        const storedBranchId = await normalizeStoredBranchId(branchId);

        try {
          if (existingId) {
            const upd = await db.query(
              `UPDATE products
               SET name = $1, sku = $2, barcode = $3, category = $4, price = $5, cost = $6,
                   stock = $7, unit = $8, tax_rate = $9, branch_id = $10,
                   supplier_id = $11, supplier_name = $12, is_active = $13,
                   last_cost = COALESCE($6, last_cost), avg_cost = COALESCE($6, avg_cost),
                   updated_at = CURRENT_TIMESTAMP
               WHERE id = $14`,
              [
                name,
                sku,
                p.barcode || '',
                p.category || 'GERAL',
                Number(p.price) || 0,
                cost,
                stock,
                String(p.unit || p.unidade || 'UN'),
                Number(p.taxRate ?? p.iva) || DEFAULT_VAT_RATE,
                storedBranchId,
                sanitizeUuid(p.supplierId),
                p.supplierName || null,
                activeInt,
                existingId,
              ],
            );
            if (upd.rowCount > 0) updated++;
          } else {
            const id = crypto.randomUUID();
            const ins = await db.query(
              `INSERT INTO products (id, name, sku, barcode, category, price, price2, price3, price4, cost, first_cost, last_cost, avg_cost, stock, unit, tax_rate, branch_id, is_active, supplier_id, supplier_name)
               VALUES ($1, $2, $3, $4, $5, $6, 0, 0, 0, $7, $7, $7, $7, $8, $9, $10, $11, $12, $13, $14)`,
              [
                id,
                name,
                sku,
                p.barcode || '',
                p.category || 'GERAL',
                Number(p.price) || 0,
                cost,
                stock,
                String(p.unit || p.unidade || 'UN'),
                Number(p.taxRate ?? p.iva) || DEFAULT_VAT_RATE,
                storedBranchId,
                activeInt,
                sanitizeUuid(p.supplierId),
                p.supplierName || null,
              ],
            );
            if (ins.rowCount > 0) inserted++;
          }
        } catch (err) {
          failed++;
          const rowError = err?.message || String(err);
          console.error('[PRODUCTS IMPORT ROW ERROR]', rowError, { sku });
          errors.push({ sku, error: rowError });
        }
      }

      console.log(`[PRODUCTS IMPORT] inserted=${inserted} updated=${updated} failed=${failed}`);
      await broadcastTable('products');
      res.status(201).json({ imported: inserted, updated, failed, errors: errors.slice(0, 50) });
    } catch (error) {
      console.error('[PRODUCTS BATCH ERROR]', error);
      res.status(500).json({ error: 'Failed to batch import products' });
    }
  });

  // Delete product (soft delete)
  router.delete('/:id', async (req, res) => {
    try {
      const { id } = req.params;
      
      await db.query('UPDATE products SET is_active = false WHERE id = $1', [id]);
      
      await broadcastTable('products');
      res.json({ success: true });
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to delete product' });
    }
  });

  return router;
};
