// Products API routes — with Optimistic Locking (Phase 3) + Multi-Price Levels
const crypto = require('crypto');
const express = require('express');
const db = require('../db');
const {
  coalesceActiveNotZero,
  coalesceMainTruthy,
  isPostgresEngine,
  sqlScalarMax,
  emptyBranchIdClause,
  catalogBranchScopeClause,
  headOfficeBranchWhere,
} = require('../lib/sqlDialect');
const productActive = (alias) => coalesceActiveNotZero(db, `${alias}.is_active`);
const branchMainActive = (alias) => coalesceMainTruthy(db, `${alias}.is_main`);
const { DEFAULT_VAT_RATE } = require('../taxDefaults');
const { checkOptimisticLock } = require('../middleware/security');
const { requirePermission } = require('../middleware/requirePermission');
const { attachUserBranchScope, resolveListBranchId, normalizeRequestedBranchId } = require('../middleware/branchScope');
const {
  findProductBySkuAndBranch,
  isUniqueSkuBranchError,
  loadMainBranchIds,
  normalizeStoredBranchId,
  canonicalSkuString,
  sqlMovementSkuKey,
  sqlCanonicalSkuText,
} = require('../lib/productSkuResolve');
const { ensureFilialProductsForWarehouse } = require('../lib/filialStockRepair');

/** Avoid running full filial reconcile on every grid poll (locks SQLite, trips health checks). */
const filialGridReconcileAt = new Map();
const FILIAL_GRID_RECONCILE_COOLDOWN_MS = 120_000;

async function ensureFilialForInventoryGrid(branchKey) {
  const key = String(branchKey || '').trim();
  if (!key) return;
  const now = Date.now();
  const last = filialGridReconcileAt.get(key) || 0;
  if (now - last < FILIAL_GRID_RECONCILE_COOLDOWN_MS) return;
  filialGridReconcileAt.set(key, now);
  try {
    await ensureFilialProductsForWarehouse(key);
  } catch (err) {
    filialGridReconcileAt.delete(key);
    console.warn('[PRODUCTS inventory-grid] filial stock reconcile:', err.message);
  }
}

function sanitizeUuid(value) {
  if (typeof value !== 'string') return value ?? null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(trimmed) ? trimmed : null;
}

/** Preserve text branch ids (e.g. branch-main) on SQLite; UUID on Postgres when valid. */
function resolveProductBranchId(req, requestedBranchId) {
  const scoped = resolveListBranchId(req, requestedBranchId);
  if (scoped === undefined) return undefined;
  if (!scoped) return null;
  const key = String(scoped).trim();
  if (!key || key === 'all') return null;
  if (db.engine === 'sqlite') return key;
  const uuid = sanitizeUuid(key);
  if (!uuid) {
    console.warn('[PRODUCTS] Ignoring invalid branchId for Postgres:', key);
    return resolveListBranchId(req, null);
  }
  return uuid;
}

function normalizeSkuKey(sku) {
  return canonicalSkuString(sku).toLowerCase();
}

function isCatalogBranchScope(branchId, mainBranchIds) {
  if (branchId == null || String(branchId).trim() === '') return true;
  return mainBranchIds.includes(String(branchId).trim());
}

function normalizeCatalogBranchKey(branchId, mainBranchIds = []) {
  const value = String(branchId ?? '').trim();
  if (!value) return 'catalog';
  if (mainBranchIds.includes(value)) return 'catalog';
  return value;
}

function normalizeNameKey(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ');
}

function skuLooksAutoGenerated(sku) {
  const value = String(sku || '').trim();
  if (!value) return true;
  return /^AUTO-/i.test(value) || /^SKU-\d{10,}/i.test(value);
}

function rowDisplayScore(row, branchId, mainBranchIds = []) {
  const stock = Number(row.stock || 0);
  const rowBranch = String(row.branch_id || '').trim();

  if (branchId && rowBranch === String(branchId)) {
    return 2_000_000 + stock;
  }

  if (branchId) {
    let score = stock;
    if (!rowBranch) score += 500_000;
    else if (!isCatalogBranchScope(rowBranch, mainBranchIds)) score += 50_000;
    if (!skuLooksAutoGenerated(row.sku)) score += 50;
    if (String(row.barcode || '').trim()) score += 25;
    return score;
  }

  let score = stock * 1000;
  if (normalizeCatalogBranchKey(row.branch_id, mainBranchIds) === 'catalog' && !rowBranch) {
    score += 500;
  }
  if (rowBranch) score += 100;
  if (!skuLooksAutoGenerated(row.sku)) score += 50;
  if (String(row.barcode || '').trim()) score += 25;
  return score;
}

function shouldMergeProductDuplicates(a, b, mainBranchIds = []) {
  const nameA = normalizeNameKey(a.name);
  const nameB = normalizeNameKey(b.name);
  if (!nameA || nameA !== nameB) return false;
  const branchA = normalizeCatalogBranchKey(a.branch_id, mainBranchIds);
  const branchB = normalizeCatalogBranchKey(b.branch_id, mainBranchIds);
  if (branchA !== branchB) return false;
  const skuA = normalizeSkuKey(a.sku);
  const skuB = normalizeSkuKey(b.sku);
  if (skuA && skuB && skuA === skuB) return true;
  const barcodeA = String(a.barcode || '').trim().toLowerCase();
  const barcodeB = String(b.barcode || '').trim().toLowerCase();
  if (barcodeA && barcodeB && barcodeA === barcodeB) return true;
  if (skuLooksAutoGenerated(a.sku) || skuLooksAutoGenerated(b.sku)) return true;
  return true;
}

function dedupeRowKey(row, mainBranchIds = []) {
  const scope = normalizeCatalogBranchKey(row.branch_id, mainBranchIds);
  const skuKey = normalizeSkuKey(row.sku);
  if (skuKey && !skuLooksAutoGenerated(row.sku)) {
    return `${scope}|sku:${skuKey}`;
  }
  const nameKey = normalizeNameKey(row.name);
  return `${scope}|name:${nameKey || row.id}`;
}

async function resolveStoredBranchId(branchId) {
  const mainBranchIds = await loadMainBranchIds();
  return normalizeStoredBranchId(branchId, mainBranchIds);
}

/** On INSERT, keep explicit warehouse id so inventory grid lists zero-stock products (branch_id = $1). */
async function resolveStoredBranchIdForCreate(branchId) {
  const key = branchId == null ? '' : String(branchId).trim();
  if (!key) return null;
  if (db.engine === 'sqlite') return key;
  const uuid = sanitizeUuid(key);
  return uuid || null;
}

async function findExistingProductForUpsert({ sku, name, branchId }) {
  const skuTrim = String(sku || '').trim();
  const nameTrim = String(name || '').trim();
  const storedBranchId = await resolveStoredBranchId(branchId);

  if (skuTrim) {
    const bySku = await findExistingProductBySku(skuTrim, storedBranchId ?? branchId);
    if (bySku) return { id: bySku, matchedBy: 'sku' };
  }

  if (nameTrim) {
    const byName = await findExistingProductByName(nameTrim, storedBranchId ?? branchId);
    if (byName?.id) return { id: byName.id, matchedBy: 'name', existingSku: byName.sku };
  }

  return null;
}

/** One row per SKU when duplicate branch/catalog rows exist (e.g. after repeated transfers). */
function dedupeProductsBySku(rows, branchId, mainBranchIds = []) {
  const bySku = new Map();
  for (const row of rows) {
    const key = dedupeRowKey(row, mainBranchIds);
    const prev = bySku.get(key);
    if (!prev) {
      bySku.set(key, row);
      continue;
    }
    const pick = rowDisplayScore(row, branchId, mainBranchIds) >= rowDisplayScore(prev, branchId, mainBranchIds) ? row : prev;
    const other = pick === row ? prev : row;
    const scopedBranch = String(branchId || '').trim();
    bySku.set(key, {
      ...pick,
      stock: scopedBranch
        ? Number(pick.stock) || 0
        : Math.max(Number(pick.stock) || 0, Number(other.stock) || 0),
      price: Math.max(Number(pick.price) || 0, Number(other.price) || 0),
      supplier_id: pick.supplier_id || other.supplier_id || null,
      supplier_name: pick.supplier_name || other.supplier_name || null,
    });
  }

  const merged = [];
  for (const row of bySku.values()) {
    const index = merged.findIndex((existing) => shouldMergeProductDuplicates(existing, row, mainBranchIds));
    if (index < 0) {
      merged.push(row);
      continue;
    }
    const prev = merged[index];
    const pick = rowDisplayScore(row, branchId, mainBranchIds) >= rowDisplayScore(prev, branchId, mainBranchIds) ? row : prev;
    const other = pick === row ? prev : row;
    const scopedBranch = String(branchId || '').trim();
    merged[index] = {
      ...pick,
      stock: scopedBranch
        ? Number(pick.stock) || 0
        : Math.max(Number(pick.stock) || 0, Number(other.stock) || 0),
      price: Math.max(Number(pick.price) || 0, Number(other.price) || 0),
      supplier_id: pick.supplier_id || other.supplier_id || null,
      supplier_name: pick.supplier_name || other.supplier_name || null,
    };
  }
  return merged;
}

async function findExistingProductBySku(skuTrim, resolvedBranchId) {
  const row = await findProductBySkuAndBranch(db, skuTrim, resolvedBranchId);
  return row?.id || null;
}

async function findExistingProductByName(nameTrim, resolvedBranchId) {
  const mainBranchIds = await loadMainBranchIds();
  if (isCatalogBranchScope(resolvedBranchId, mainBranchIds)) {
    const params = [nameTrim];
    let sql = `
      SELECT id, sku FROM products
      WHERE ${coalesceActiveNotZero(db, 'is_active')}
        AND LOWER(TRIM(COALESCE(name, ''))) = LOWER($1)
        AND (
          ${emptyBranchIdClause(db, 'branch_id')}`;
    for (const id of mainBranchIds) {
      params.push(id);
      sql += ` OR branch_id = $${params.length}`;
    }
    sql += `
        )
      ORDER BY CASE WHEN ${emptyBranchIdClause(db, 'branch_id')} THEN 0 ELSE 1 END,
               created_at ASC
      LIMIT 1`;
    const result = await db.query(sql, params);
    return result.rows[0] || null;
  }

  const result = await db.query(
    `SELECT id, sku FROM products
     WHERE ${coalesceActiveNotZero(db, 'is_active')}
       AND LOWER(TRIM(COALESCE(name, ''))) = LOWER($1)
       AND branch_id = $2
     ORDER BY created_at ASC
     LIMIT 1`,
    [nameTrim, resolvedBranchId],
  );
  return result.rows[0] || null;
}

/** Fast grid list: products.stock only (no per-row movement aggregation). */
function branchListStockSql(lightList) {
  if (lightList) {
    return `CASE
              WHEN bp.id IS NOT NULL THEN COALESCE(bp.stock, 0)
              WHEN p.branch_id = $1 THEN COALESCE(p.stock, 0)
              ELSE 0
            END`;
  }
  return `CASE
              WHEN p.sku IS NOT NULL AND TRIM(p.sku) != '' AND EXISTS (
                SELECT 1
                FROM stock_movements sm
                INNER JOIN products pm ON pm.id = sm.product_id
                WHERE sm.warehouse_id = $1
                  AND LOWER(TRIM(COALESCE(pm.sku, ''))) = LOWER(TRIM(p.sku))
              ) THEN ${sqlScalarMax(db, '0', `COALESCE((
                SELECT SUM(
                  CASE
                    WHEN sm.movement_type = 'IN' THEN sm.quantity
                    WHEN sm.movement_type = 'OUT' THEN -sm.quantity
                    ELSE 0
                  END
                )
                FROM stock_movements sm
                INNER JOIN products pm ON pm.id = sm.product_id
                WHERE sm.warehouse_id = $1
                  AND LOWER(TRIM(COALESCE(pm.sku, ''))) = LOWER(TRIM(p.sku))
              ), 0)`)}
              WHEN bp.id IS NOT NULL THEN COALESCE(bp.stock, 0)
              WHEN p.branch_id = $1 THEN COALESCE(p.stock, 0)
              ELSE 0
            END`;
}

function branchListMovementExistsClause(lightList) {
  if (lightList) return '';
  return `
              OR EXISTS (
                SELECT 1
                FROM stock_movements sm
                WHERE sm.warehouse_id = $1
                  AND sm.product_id = p.id
              )`;
}

/** Columns returned by inventory grid endpoints (minimal payload). */
const INVENTORY_GRID_COLUMNS = `
            id, name, sku, barcode, category, price, cost,
            first_cost, last_cost, avg_cost, stock, unit, tax_rate,
            branch_id, supplier_id, supplier_name`;

const INVENTORY_LIST_COLUMNS = `
            id, name, sku, barcode, category, price, price2, price3, price4,
            cost, first_cost, last_cost, avg_cost, stock, unit, tax_rate,
            branch_id, supplier_id, supplier_name, is_active, created_at, updated_at`;

function mergeGridSkuRow(prev, row, warehouseBranchId, mainBranchIds = []) {
  const pick =
    rowDisplayScore(row, warehouseBranchId, mainBranchIds)
    >= rowDisplayScore(prev, warehouseBranchId, mainBranchIds)
      ? row
      : prev;
  const other = pick === row ? prev : row;
  const scoped = String(warehouseBranchId || '').trim();
  const maxN = (a, b) => Math.max(Number(a) || 0, Number(b) || 0);
  return {
    ...pick,
    stock: scoped ? Number(pick.stock) || 0 : maxN(pick.stock, other.stock),
    price: maxN(pick.price, other.price),
    cost: maxN(pick.cost, other.cost),
    first_cost: maxN(pick.first_cost, other.first_cost),
    last_cost: maxN(pick.last_cost, other.last_cost),
    avg_cost: maxN(pick.avg_cost, other.avg_cost),
  };
}

function dedupeRowsBySkuFast(rows, warehouseBranchId, mainBranchIds = []) {
  const bySku = new Map();
  for (const row of rows) {
    const key = normalizeSkuKey(row.sku) || String(row.id);
    const prev = bySku.get(key);
    if (!prev) {
      bySku.set(key, row);
      continue;
    }
    bySku.set(key, mergeGridSkuRow(prev, row, warehouseBranchId, mainBranchIds));
  }
  return Array.from(bySku.values());
}

/** One scan of movements per warehouse → stock by SKU (accurate qty, fast). */
function sqlStockBySkuCte() {
  const skuKey = sqlMovementSkuKey('pm');
  return `
    stock_by_sku AS (
      SELECT
        ${skuKey} AS sku_key,
        CASE
          WHEN COALESCE(SUM(
            CASE
              WHEN sm.movement_type = 'IN' THEN sm.quantity
              WHEN sm.movement_type = 'OUT' THEN -sm.quantity
              ELSE 0
            END
          ), 0) < 0 THEN 0
          ELSE COALESCE(SUM(
            CASE
              WHEN sm.movement_type = 'IN' THEN sm.quantity
              WHEN sm.movement_type = 'OUT' THEN -sm.quantity
              ELSE 0
            END
          ), 0)
        END AS ledger_stock
      FROM stock_movements sm
      INNER JOIN products pm ON pm.id = sm.product_id
      WHERE sm.warehouse_id = $1
      GROUP BY ${skuKey}
    )`;
}

/**
 * Stock for this warehouse only.
 * Catalog/master rows (branch_id != warehouse) must NOT use products.stock from sede — that caused
 * Soyo showing Main qty and HQ totals doubling when summing filiais.
 */
/** Hide catalog only when an active filial row exists for the same SKU (not merely same name). */
function sqlHideCatalogWhenFilialHasSameSku() {
  return `
            AND NOT EXISTS (
              SELECT 1 FROM products bx
              WHERE ${productActive('bx')}
                AND bx.branch_id = $1
                AND TRIM(COALESCE(p.sku, '')) != ''
                AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
            )`;
}

/** Pick one display row per SKU: filial row first, then row with most movements at this warehouse. */
function sqlPickProductIdForSkuAtWarehouse(catalogPickClause) {
  const p2Key = sqlMovementSkuKey('p2');
  return `
            p.id = (
              SELECT p2.id
              FROM products p2
              WHERE ${p2Key} = ms.sku_key
                AND (
                  p2.branch_id = $1
                  OR ${catalogPickClause}
                  OR p2.id IN (
                    SELECT DISTINCT sm.product_id
                    FROM stock_movements sm
                    WHERE sm.warehouse_id = $1
                  )
                )
              ORDER BY
                CASE WHEN COALESCE(p2.sku, '') LIKE '%-DUP-%' THEN 1 ELSE 0 END,
                CASE WHEN p2.branch_id = $1 THEN 0 ELSE 1 END,
                (
                  SELECT COUNT(*)
                  FROM stock_movements sm
                  WHERE sm.product_id = p2.id
                    AND sm.warehouse_id = $1
                ) DESC,
                p2.updated_at DESC,
                p2.created_at DESC
              LIMIT 1
            )`;
}

function sqlGridStockExpr(alias = 'p', warehouseBranchParam = '$1') {
  return `CASE
            WHEN ${alias}.branch_id = ${warehouseBranchParam} THEN
              CASE
                WHEN COALESCE(sbs.ledger_stock, ${alias}.stock, 0) < 0 THEN 0
                ELSE COALESCE(sbs.ledger_stock, ${alias}.stock, 0)
              END
            ELSE
              CASE
                WHEN COALESCE(sbs.ledger_stock, 0) < 0 THEN 0
                ELSE COALESCE(sbs.ledger_stock, 0)
              END
          END`;
}

/** Row-level PVP for grid SQL — cross-SKU hints applied after query via enrichRowsWithSellingPrices. */
function sqlGridRowPriceExpr(alias = 'p') {
  // Price 1 is the authoritative base price (entered manually). Do NOT blend it with
  // price2 — POS/sales select a tier by level, and returning MAX(price, price2) here
  // made level 1 (and any empty tier that falls back to `price`) resolve to price2.
  return `COALESCE(${alias}.price, 0)`;
}

/** Inventory-grid display price: keep real price1; only fill zeros from siblings / price2. */
function sqlGridDisplayPriceExpr(alias = 'p') {
  return `CASE
    WHEN COALESCE(${alias}.price, 0) > 0.0001 THEN COALESCE(${alias}.price, 0)
    ELSE ${sqlGridSellingPriceExpr(alias)}
  END`;
}

/** Latest purchase/transfer IN unit cost for this product at the active warehouse ($1). */
function sqlLastInUnitCostExpr(alias = 'p') {
  return `(
    SELECT sm.unit_cost
    FROM stock_movements sm
    WHERE sm.product_id = ${alias}.id
      AND sm.warehouse_id = $1
      AND sm.movement_type = 'IN'
      AND COALESCE(sm.unit_cost, 0) > 0.0001
    ORDER BY sm.created_at DESC
    LIMIT 1
  )`;
}

/** Cost column for inventory grid — fill zeros from last stock IN. */
function sqlGridDisplayCostExpr(alias, field) {
  return `CASE
    WHEN COALESCE(${alias}.${field}, 0) > 0.0001 THEN ${alias}.${field}
    ELSE COALESCE(${sqlLastInUnitCostExpr(alias)}, ${alias}.cost, 0)
  END`;
}

/** Best selling price for this SKU across catalog + filial rows (fixes Qtd > 0 filial-only rows). */
function sqlGridSellingPriceExpr(alias = 'p') {
  const rowPvp = sqlScalarMax(db, `COALESCE(${alias}.price, 0)`, `COALESCE(${alias}.price2, 0)`);
  const pxWhere = `
    WHERE ${productActive('px')}
      AND TRIM(COALESCE(px.sku, '')) != ''
      AND ${sqlMovementSkuKey('px')} = ${sqlMovementSkuKey(alias)}`;
  const siblingMax = isPostgresEngine(db)
    ? `(
    SELECT MAX(sub_val)
    FROM (
      SELECT ${sqlScalarMax(db, 'COALESCE(px.price, 0)', 'COALESCE(px.price2, 0)')} AS sub_val
      FROM products px
      ${pxWhere}
    ) sku_prices
  )`
    : `(
    SELECT MAX(MAX(COALESCE(px.price, 0), COALESCE(px.price2, 0)))
    FROM products px
    ${pxWhere}
  )`;
  return sqlScalarMax(db, rowPvp, `COALESCE(${siblingMax}, 0)`);
}

/** Inventory grid filial: show every SKU with stock movements at this warehouse (transfer receive). */
async function listProductsForBranchInventoryGrid(branchKey) {
  const mainBranchIds = await loadMainBranchIds();
  const rowPrice = sqlGridDisplayPriceExpr('p');
  const rowCost = sqlGridDisplayCostExpr('p', 'cost');
  const rowFirstCost = sqlGridDisplayCostExpr('p', 'first_cost');
  const rowLastCost = sqlGridDisplayCostExpr('p', 'last_cost');
  const rowAvgCost = sqlGridDisplayCostExpr('p', 'avg_cost');
  const mainIn =
    mainBranchIds.length > 0
      ? mainBranchIds.map((_, i) => `$${i + 2}`).join(', ')
      : "''";
  const params = [branchKey, ...mainBranchIds];
  const catalogBranchClause = catalogBranchScopeClause(db, 'p', mainIn);
  const catalogPickClause = catalogBranchScopeClause(db, 'p2', mainIn);

  const query = `
          WITH ${sqlStockBySkuCte()},
          movement_skus AS (
            SELECT sku_key, ledger_stock
            FROM stock_by_sku
            WHERE ledger_stock > 0.0001
          )
          SELECT
            p.id,
            p.name,
            p.sku,
            p.barcode,
            p.category,
            ${rowPrice} AS price,
            p.price2,
            p.price3,
            p.price4,
            ${rowCost} AS cost,
            ${rowFirstCost} AS first_cost,
            ${rowLastCost} AS last_cost,
            ${rowAvgCost} AS avg_cost,
            COALESCE(ms.ledger_stock, sbs.ledger_stock, 0) AS stock,
            p.unit,
            p.tax_rate,
            CASE WHEN p.branch_id = $1 THEN p.branch_id ELSE $1 END AS branch_id,
            p.supplier_id,
            p.supplier_name
          FROM products p
          INNER JOIN movement_skus ms
            ON ${sqlMovementSkuKey('p')} = ms.sku_key
          LEFT JOIN stock_by_sku sbs
            ON ms.sku_key = sbs.sku_key
          WHERE ${sqlPickProductIdForSkuAtWarehouse(catalogPickClause)}

          UNION ALL

          SELECT
            p.id,
            p.name,
            p.sku,
            p.barcode,
            p.category,
            ${rowPrice} AS price,
            p.price2,
            p.price3,
            p.price4,
            ${rowCost} AS cost,
            ${rowFirstCost} AS first_cost,
            ${rowLastCost} AS last_cost,
            ${rowAvgCost} AS avg_cost,
            ${sqlGridStockExpr('p')} AS stock,
            p.unit,
            p.tax_rate,
            p.branch_id,
            p.supplier_id,
            p.supplier_name
          FROM products p
          LEFT JOIN stock_by_sku sbs
            ON ${sqlMovementSkuKey('p')} = sbs.sku_key
          WHERE ${productActive('p')}
            AND p.branch_id = $1
            AND TRIM(COALESCE(p.sku, '')) != ''
            AND NOT EXISTS (
              SELECT 1 FROM movement_skus ms
              WHERE ms.sku_key = ${sqlMovementSkuKey('p')}
            )

          UNION ALL

          SELECT
            p.id,
            p.name,
            p.sku,
            p.barcode,
            p.category,
            ${rowPrice} AS price,
            p.price2,
            p.price3,
            p.price4,
            ${rowCost} AS cost,
            ${rowFirstCost} AS first_cost,
            ${rowLastCost} AS last_cost,
            ${rowAvgCost} AS avg_cost,
            ${sqlGridStockExpr('p')} AS stock,
            p.unit,
            p.tax_rate,
            $1 AS branch_id,
            p.supplier_id,
            p.supplier_name
          FROM products p
          LEFT JOIN stock_by_sku sbs
            ON ${sqlMovementSkuKey('p')} = sbs.sku_key
          WHERE ${productActive('p')}
            AND TRIM(COALESCE(p.sku, '')) != ''
            AND ${catalogBranchClause}
            ${sqlHideCatalogWhenFilialHasSameSku()}
            AND NOT EXISTS (
              SELECT 1 FROM movement_skus ms
              WHERE ms.sku_key = ${sqlMovementSkuKey('p')}
            )
          ORDER BY name`;
  const result = await db.query(query, params);
  return dedupeRowsBySkuFast(result.rows, branchKey, mainBranchIds);
}

function mergeConsolidatedSkuRow(bySku, row, mainBranchIds) {
  const key = normalizeSkuKey(row.sku) || String(row.id);
  const qty = Number(row.stock) || 0;
  const prev = bySku.get(key);
  if (!prev) {
    bySku.set(key, { ...row, stock: qty });
    return;
  }
  const pick =
    rowDisplayScore(row, undefined, mainBranchIds) >= rowDisplayScore(prev, undefined, mainBranchIds)
      ? row
      : prev;
  const other = pick === row ? prev : row;
  const maxN = (a, b) => Math.max(Number(a) || 0, Number(b) || 0);
  bySku.set(key, {
    ...pick,
    supplier_id: pick.supplier_id || other.supplier_id || null,
    supplier_name: pick.supplier_name || other.supplier_name || null,
    stock: (Number(prev.stock) || 0) + qty,
    price: maxN(pick.price, other.price),
    cost: maxN(pick.cost, other.cost),
    first_cost: maxN(pick.first_cost, other.first_cost),
    last_cost: maxN(pick.last_cost, other.last_cost),
    avg_cost: maxN(pick.avg_cost, other.avg_cost),
  });
}

/** HQ all branches: sum each warehouse's grid (one row per SKU per branch), then merge by SKU. */
async function listInventoryConsolidatedByBranches() {
  const branchesResult = await db.query(
    `SELECT id FROM branches ORDER BY name`,
  );
  const mainBranchIds = await loadMainBranchIds();
  const bySku = new Map();
  const branchRows = await Promise.all(
    (branchesResult.rows || []).map(async (b) => {
      const branchKey = String(b.id).trim();
      try {
        const rows = await listProductsForBranchInventoryGrid(branchKey);
        return dedupeProductsBySku(rows, branchKey, mainBranchIds);
      } catch (err) {
        console.error('[PRODUCTS inventory-grid] branch', b.id, err.message);
        return [];
      }
    }),
  );
  for (const deduped of branchRows) {
    for (const row of deduped) {
      mergeConsolidatedSkuRow(bySku, row, mainBranchIds);
    }
  }
  return Array.from(bySku.values());
}

/** Fast picker list for PO/PI/sales — no movement CTE or per-row price subqueries. */
async function listProductsForBranchFast(branchKey) {
  const mainBranchIds = await loadMainBranchIds();
  const mainIn =
    mainBranchIds.length > 0
      ? mainBranchIds.map((_, i) => `$${i + 2}`).join(', ')
      : "''";
  const params = [branchKey, ...mainBranchIds];
  const catalogBranchClause = catalogBranchScopeClause(db, 'p', mainIn);
  // Price 1 is the authoritative base; never blend with price2 (see sqlGridRowPriceExpr).
  const rowPrice = 'COALESCE(p.price, 0)';
  const branchStock = `CASE WHEN p.branch_id = $1 THEN COALESCE(p.stock, 0) ELSE 0 END`;

  const listSelect = `
            p.id, p.name, p.sku, p.barcode, p.category,
            ${rowPrice} AS price, p.price2, p.price3, p.price4,
            p.cost, p.first_cost, p.last_cost, p.avg_cost,
            ${branchStock} AS stock,
            p.unit, p.tax_rate, p.branch_id, p.supplier_id, p.supplier_name,
            p.is_active, p.created_at, p.updated_at`;

  const query = `
          SELECT ${listSelect}
          FROM products p
          WHERE ${productActive('p')} AND p.branch_id = $1

          UNION ALL

          SELECT
            p.id, p.name, p.sku, p.barcode, p.category,
            ${rowPrice} AS price, p.price2, p.price3, p.price4,
            p.cost, p.first_cost, p.last_cost, p.avg_cost,
            0 AS stock,
            p.unit, p.tax_rate,
            $1 AS branch_id,
            p.supplier_id, p.supplier_name,
            p.is_active, p.created_at, p.updated_at
          FROM products p
          WHERE ${productActive('p')}
            AND TRIM(COALESCE(p.sku, '')) != ''
            AND ${catalogBranchClause}
            ${sqlHideCatalogWhenFilialHasSameSku()}
          ORDER BY name`;
  const result = await db.query(query, params);
  return dedupeRowsBySkuFast(result.rows, branchKey, mainBranchIds);
}

let sellingHintsCache = null;
let sellingHintsCacheAt = 0;
const SELLING_HINTS_CACHE_MS = 120_000;

/** Best selling price per canonical SKU (catalog + filial + PVP1 on purchase lines). */
async function loadSellingPriceHintsBySku() {
  const now = Date.now();
  if (sellingHintsCache && now - sellingHintsCacheAt < SELLING_HINTS_CACHE_MS) {
    return sellingHintsCache;
  }

  const bySku = new Map();

  const productRows = await db.query(
    `SELECT ${sqlCanonicalSkuText('p')} AS sku_key, p.price, p.price2
     FROM products p
     WHERE ${productActive('p')}
       AND TRIM(COALESCE(p.sku, '')) != ''`,
  );
  for (const row of productRows.rows || []) {
    const key = String(row.sku_key || '').trim().toLowerCase();
    if (!key) continue;
    const best = Math.max(
      Number(bySku.get(key) || 0),
      Number(row.price) || 0,
      Number(row.price2) || 0,
    );
    if (best > 0) bySku.set(key, best);
  }

  try {
    const invoices = await db.query(
      `SELECT lines_json FROM purchase_invoices
       ORDER BY date DESC, updated_at DESC
       LIMIT 800`,
    );
    for (const inv of invoices.rows || []) {
      let lines = inv.lines_json;
      if (typeof lines === 'string') {
        try {
          lines = JSON.parse(lines);
        } catch {
          lines = [];
        }
      }
      if (!Array.isArray(lines)) continue;
      for (const line of lines) {
        const rawSku = line.productCode || line.product_code || '';
        const key = canonicalSkuString(rawSku).toLowerCase();
        if (!key) continue;
        const p1 = Number(line.price1 ?? line.price ?? 0);
        if (p1 > 0) bySku.set(key, Math.max(Number(bySku.get(key) || 0), p1));
      }
    }
  } catch (err) {
    console.warn('[PRODUCTS] purchase price hints:', err.message);
  }

  sellingHintsCache = bySku;
  sellingHintsCacheAt = now;
  return bySku;
}

function invalidateSellingHintsCache() {
  sellingHintsCache = null;
  sellingHintsCacheAt = 0;
}

let purchaseSupplierCache = null;
let purchaseSupplierCacheAt = 0;
const PURCHASE_SUPPLIER_CACHE_MS = 120_000;

/** Latest supplier per SKU from confirmed purchase invoices (for inventory grid). */
async function loadLatestPurchaseSupplierBySku() {
  const now = Date.now();
  if (purchaseSupplierCache && now - purchaseSupplierCacheAt < PURCHASE_SUPPLIER_CACHE_MS) {
    return purchaseSupplierCache;
  }

  const bySku = new Map();
  try {
    const invoices = await db.query(
      `SELECT supplier_id, supplier_name, lines_json, date, updated_at
       FROM purchase_invoices
       WHERE TRIM(COALESCE(supplier_name, '')) != ''
       ORDER BY date DESC, updated_at DESC
       LIMIT 800`,
    );
    for (const inv of invoices.rows || []) {
      const supplierName = String(inv.supplier_name || '').trim();
      if (!supplierName) continue;
      const supplierId = String(inv.supplier_id || '').trim() || null;
      let lines = inv.lines_json;
      if (typeof lines === 'string') {
        try {
          lines = JSON.parse(lines);
        } catch {
          lines = [];
        }
      }
      if (!Array.isArray(lines)) continue;
      for (const line of lines) {
        const rawSku = line.productCode || line.product_code || line.sku || '';
        const key = canonicalSkuString(rawSku).toLowerCase();
        if (!key || bySku.has(key)) continue;
        bySku.set(key, { supplier_id: supplierId, supplier_name: supplierName });
      }
    }
  } catch (err) {
    console.warn('[PRODUCTS] purchase supplier hints:', err.message);
  }

  purchaseSupplierCache = bySku;
  purchaseSupplierCacheAt = now;
  return bySku;
}

function enrichRowsWithPurchaseSuppliers(rows, supplierBySkuPreloaded) {
  const bySku = supplierBySkuPreloaded;
  if (!bySku?.size) return rows;
  return rows.map((row) => {
    const hasName = row.supplier_name != null && String(row.supplier_name).trim() !== '';
    if (hasName) return row;
    const key = canonicalSkuString(row.sku).toLowerCase();
    if (!key) return row;
    const hit = bySku.get(key);
    if (!hit?.supplier_name) return row;
    return {
      ...row,
      supplier_id: row.supplier_id || hit.supplier_id || null,
      supplier_name: hit.supplier_name,
    };
  });
}

function invalidatePurchaseSupplierCache() {
  purchaseSupplierCache = null;
  purchaseSupplierCacheAt = 0;
}

function enrichInventoryGridSellingPrices(rows, priceBySku) {
  if (!priceBySku?.size) return rows;
  return rows.map((row) => {
    // Price 1 is the authoritative base price entered on the product. Only SEED it from the
    // selling-price hint when it is missing (zero); never RAISE a real price1, otherwise
    // POS/sales price-level selection (level 1 = price1) would resolve to a blended value.
    const cur = Number(row.price) || 0;
    if (cur > 0) return row;
    const key = canonicalSkuString(row.sku).toLowerCase();
    if (!key) return row;
    const hint = Number(priceBySku.get(key) || 0);
    if (hint <= 0) return row;
    return { ...row, price: hint };
  });
}

/** Write hinted selling price onto all rows for this SKU when DB price is still zero. */
async function persistSellingPricesFromHints(priceBySku) {
  if (!priceBySku?.size) return 0;
  let updated = 0;
  for (const [skuKey, price] of priceBySku) {
    const p = Number(price);
    if (!skuKey || p <= 0) continue;
    const result = await db.query(
      `UPDATE products
       SET price = $1, updated_at = CURRENT_TIMESTAMP
       WHERE ${coalesceActiveNotZero(db, 'is_active')}
         AND LOWER(TRIM(${sqlCanonicalSkuText('products')})) = LOWER($2)
         AND COALESCE(price, 0) < $1`,
      [p, skuKey],
    );
    updated += result.rowCount || 0;
  }
  return updated;
}

/** Set by module.exports — used after persisting selling prices from hints. */
let onProductsTableChange = null;

/** Apply global PVP hints to rows — read-only (no DB writes on list/grid; avoids SQLite lock). */
async function enrichRowsWithSellingPrices(rows, priceBySkuPreloaded) {
  const priceBySku = priceBySkuPreloaded ?? (await loadSellingPriceHintsBySku());
  return enrichInventoryGridSellingPrices(rows, priceBySku);
}

function mergeFastPickerRowsIntoGrid(gridRows, fastRows) {
  const bySku = new Map();
  for (const row of gridRows) {
    const key = normalizeSkuKey(row.sku) || String(row.id);
    bySku.set(key, row);
  }
  for (const row of fastRows) {
    const key = normalizeSkuKey(row.sku) || String(row.id);
    if (!key || bySku.has(key)) continue;
    bySku.set(key, row);
  }
  return Array.from(bySku.values());
}

async function listInventoryGridRows(branchId, consolidated, priceBySkuPreloaded) {
  const mainBranchIds = await loadMainBranchIds();
  let rows;
  if (consolidated) {
    const branchesResult = await db.query('SELECT id FROM branches ORDER BY name');
    for (const b of branchesResult.rows || []) {
      await ensureFilialForInventoryGrid(String(b.id).trim());
    }
    rows = await listInventoryConsolidatedByBranches();
  } else {
    const branchKey = String(branchId || '').trim();
    if (!branchKey) return [];
    await ensureFilialForInventoryGrid(branchKey);
    try {
      rows = await listProductsForBranchInventoryGrid(branchKey);
      const fastRows = await listProductsForBranchFast(branchKey);
      rows = mergeFastPickerRowsIntoGrid(rows, fastRows);
      rows = dedupeProductsBySku(rows, branchKey, mainBranchIds);
    } catch (err) {
      console.error('[PRODUCTS inventory-grid] filial query failed, fallback:', err.message);
      rows = await listProductsForBranchFast(branchKey);
      rows = dedupeProductsBySku(rows, branchKey, mainBranchIds);
    }
  }
  const supplierBySku = await loadLatestPurchaseSupplierBySku();
  rows = enrichRowsWithPurchaseSuppliers(rows, supplierBySku);
  return enrichRowsWithSellingPrices(rows, priceBySkuPreloaded);
}

async function listProductsForBranch(branchKey, lightList) {
  const mainBranchIds = await loadMainBranchIds();
  const branchKeyStr = String(branchKey).trim();
  let rows;
  if (lightList) {
    rows = await listProductsForBranchFast(branchKey);
    rows = dedupeProductsBySku(rows, branchKeyStr, mainBranchIds);
    return rows;
  } else {
  const stockSql = branchListStockSql(lightList);
  const movementExistsSql = branchListMovementExistsClause(lightList);
  const query = `
          SELECT
            COALESCE(bp.id, p.id) AS id,
            COALESCE(bp.name, p.name) AS name,
            COALESCE(bp.sku, p.sku) AS sku,
            COALESCE(bp.barcode, p.barcode) AS barcode,
            COALESCE(bp.category, p.category) AS category,
            ${sqlScalarMax(db, 'COALESCE(bp.price, 0)', 'COALESCE(p.price, 0)')} AS price,
            ${sqlScalarMax(db, 'COALESCE(bp.price2, 0)', 'COALESCE(p.price2, 0)')} AS price2,
            ${sqlScalarMax(db, 'COALESCE(bp.price3, 0)', 'COALESCE(p.price3, 0)')} AS price3,
            ${sqlScalarMax(db, 'COALESCE(bp.price4, 0)', 'COALESCE(p.price4, 0)')} AS price4,
            COALESCE(bp.cost, p.cost) AS cost,
            COALESCE(bp.first_cost, p.first_cost, bp.cost, p.cost) AS first_cost,
            COALESCE(bp.last_cost, p.last_cost, bp.cost, p.cost) AS last_cost,
            COALESCE(bp.avg_cost, p.avg_cost, bp.cost, p.cost) AS avg_cost,
            ${stockSql} AS stock,
            COALESCE(bp.unit, p.unit) AS unit,
            COALESCE(bp.tax_rate, p.tax_rate) AS tax_rate,
            COALESCE(bp.branch_id, $1) AS branch_id,
            COALESCE(bp.supplier_id, p.supplier_id) AS supplier_id,
            COALESCE(bp.supplier_name, p.supplier_name) AS supplier_name,
            COALESCE(bp.is_active, p.is_active) AS is_active,
            COALESCE(bp.created_at, p.created_at) AS created_at,
            COALESCE(bp.updated_at, p.updated_at) AS updated_at
          FROM products p
          LEFT JOIN products bp ON bp.id = (
            SELECT bx.id
            FROM products bx
            WHERE ${productActive('bx')}
              AND bx.branch_id = $1
              AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
              AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
            ORDER BY bx.updated_at DESC, bx.created_at DESC
            LIMIT 1
          )
          WHERE ${productActive('p')}
            AND (
              p.branch_id = $1
              OR bp.id IS NOT NULL
              OR (
                ${emptyBranchIdClause(db, 'p.branch_id')}
                AND NOT EXISTS (
                  SELECT 1 FROM products bx
                  WHERE ${productActive('bx')} AND bx.branch_id = $1
                    AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
                    AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
                )
              )
              OR (
                p.branch_id IN (
                  SELECT id FROM branches
                  WHERE ${headOfficeBranchWhere(db)}
                )
                AND p.sku IS NOT NULL AND TRIM(p.sku) != ''
                AND NOT EXISTS (
                  SELECT 1 FROM products bx
                  WHERE ${productActive('bx')} AND bx.branch_id = $1
                    AND LOWER(TRIM(COALESCE(bx.sku, ''))) = LOWER(TRIM(p.sku))
                )
              )${movementExistsSql}
            )
          ORDER BY name`;
  try {
    const result = await db.query(query, [branchKey]);
    rows = dedupeProductsBySku(result.rows, branchKeyStr, mainBranchIds);
  } catch (fullListErr) {
    console.error('[PRODUCTS] full branch list failed, using fast list:', fullListErr.message);
    rows = await listProductsForBranchFast(branchKey);
    rows = dedupeProductsBySku(rows, branchKeyStr, mainBranchIds);
  }
  }
  return enrichRowsWithSellingPrices(rows);
}

/** Stock movements or sale lines for this product (any row sharing the same canonical SKU). */
async function productTransactionCounts(productId) {
  const id = String(productId || '').trim();
  if (!id) {
    return { movements: 0, sales: 0, total: 0, deletable: true };
  }

  const skuResult = await db.query('SELECT sku FROM products WHERE id = $1', [id]);
  const sku = canonicalSkuString(skuResult.rows?.[0]?.sku || '');

  let ids = [id];
  if (sku) {
    const idsResult = await db.query(
      `SELECT id FROM products
       WHERE LOWER(TRIM(${sqlCanonicalSkuText('products')})) = LOWER($1)`,
      [sku],
    );
    const fromSku = (idsResult.rows || []).map((r) => r.id).filter(Boolean);
    if (fromSku.length) ids = [...new Set(fromSku)];
  }

  const ph = ids.map((_, i) => `$${i + 1}`).join(', ');

  let movements = 0;
  let sales = 0;
  try {
    const mov = await db.query(
      `SELECT COUNT(*) AS n FROM stock_movements WHERE product_id IN (${ph})`,
      ids,
    );
    movements = Number(mov.rows?.[0]?.n || 0);
  } catch (_) {
    movements = 0;
  }
  try {
    const sal = await db.query(
      `SELECT COUNT(*) AS n FROM sale_items WHERE product_id IN (${ph})`,
      ids,
    );
    sales = Number(sal.rows?.[0]?.n || 0);
  } catch (_) {
    sales = 0;
  }

  const total = movements + sales;
  return { movements, sales, total, deletable: total === 0 };
}

module.exports = function(broadcastTable) {
  onProductsTableChange = broadcastTable;
  const router = express.Router();
  router.use(attachUserBranchScope);

  /** HQ inventory grid: one HTTP round-trip, summed stock per SKU (fast/light). */
  router.get('/inventory-consolidated', async (req, res) => {
    try {
      const scope = req.branchScope;
      if (scope?.forceBranchId) {
        return res.status(403).json({ error: 'Consolidated inventory is for head office only' });
      }
      if (scope && !scope.isHeadOffice && !scope.isGlobalAdmin) {
        return res.status(403).json({ error: 'Consolidated inventory is for head office only' });
      }
      const rows = await listInventoryConsolidatedByBranches();
      res.json(rows);
    } catch (error) {
      console.error('[PRODUCTS inventory-consolidated]', error);
      res.status(500).json({ error: 'Failed to load consolidated inventory' });
    }
  });

  /** Reconcile filial stock from movements only (does not create product rows). */
  router.post('/repair-filial-stock', requirePermission('admin_settings'), async (req, res) => {
    try {
      const branchId = resolveListBranchId(req, req.query.branchId || req.body?.branchId);
      if (!branchId) {
        return res.status(400).json({ error: 'branchId is required' });
      }
      const repair = await ensureFilialProductsForWarehouse(branchId);
      const rows = await listProductsForBranchInventoryGrid(branchId);
      const mainBranchIds = await loadMainBranchIds();
      const deduped = dedupeProductsBySku(rows, String(branchId).trim(), mainBranchIds);
      await broadcastTable('products');
      res.json({
        success: true,
        branchId,
        repair,
        rows: deduped,
        count: deduped.length,
        dbPath: process.env.SQLITE_PATH || null,
      });
    } catch (error) {
      console.error('[PRODUCTS repair-filial-stock]', error);
      res.status(500).json({ error: error.message || 'Repair failed' });
    }
  });

  /**
   * Bulk-apply tier pricing across the whole catalog: Price N = Price 1 x (1 + pct/100).
   * Overwrites price2/3/4 for every active product that has a Price 1 > 0 (products with
   * no base price are skipped so we never zero-out their tiers). Only tiers whose percentage
   * is supplied are touched. One-time action (no stored rule).
   */
  router.post('/bulk-tier-pricing', requirePermission('price_edit'), async (req, res) => {
    try {
      const body = req.body || {};
      const parsePct = (v) => {
        if (v == null || v === '') return null;
        const n = Number(v);
        return Number.isFinite(n) ? n : NaN;
      };
      const pcts = {
        price2: parsePct(body.price2Pct),
        price3: parsePct(body.price3Pct),
        price4: parsePct(body.price4Pct),
      };
      if (Object.values(pcts).some((n) => Number.isNaN(n))) {
        return res.status(400).json({ error: 'Percentages must be numbers' });
      }
      const sets = [];
      const params = [];
      let idx = 1;
      for (const [col, pct] of Object.entries(pcts)) {
        if (pct == null) continue;
        // Round in SQL; CAST keeps Postgres happy (ROUND(double, int) does not exist there).
        sets.push(`${col} = ROUND(CAST(price * $${idx} AS numeric), 2)`);
        params.push(1 + pct / 100);
        idx += 1;
      }
      if (sets.length === 0) {
        return res.status(400).json({ error: 'Provide at least one of price2Pct, price3Pct, price4Pct' });
      }
      const sql = `UPDATE products
                   SET ${sets.join(', ')}, updated_at = CURRENT_TIMESTAMP
                   WHERE price > 0 AND ${coalesceActiveNotZero(db, 'is_active')}`;
      const result = await db.query(sql, params);
      await broadcastTable('products');
      console.log(`[PRODUCTS bulk-tier-pricing] updated=${result.rowCount} pcts=${JSON.stringify(pcts)}`);
      res.json({ success: true, updated: result.rowCount || 0 });
    } catch (error) {
      console.error('[PRODUCTS bulk-tier-pricing]', error);
      res.status(500).json({ error: error.message || 'Bulk tier pricing failed' });
    }
  });

  /** Best PVP per SKU (catalog + all filials + purchase PVP1) — for POS and single-branch inventory. */
  router.get('/selling-prices', async (req, res) => {
    try {
      const priceBySku = await loadSellingPriceHintsBySku();
      res.setHeader('Cache-Control', 'private, max-age=30');
      res.json(Object.fromEntries(priceBySku));
    } catch (error) {
      console.error('[PRODUCTS selling-prices]', error);
      res.status(500).json({ error: 'Failed to load selling prices' });
    }
  });

  /** Inventory lista tab — slim JSON, single query, optional session cache on client. */
  router.get('/inventory-grid', async (req, res) => {
    try {
      const wantConsolidated =
        req.query.consolidated === '1' || req.query.consolidated === 'true';
      let branchId = resolveListBranchId(req, req.query.branchId);
      if (wantConsolidated) {
        const scope = req.branchScope;
        if (scope?.forceBranchId) {
          return res.status(403).json({ error: 'Consolidated inventory is for head office only' });
        }
        if (scope && !scope.isHeadOffice && !scope.isGlobalAdmin) {
          return res.status(403).json({ error: 'Consolidated inventory is for head office only' });
        }
        branchId = null;
      } else if (branchId === undefined) {
        return res.json({ rows: [], count: 0 });
      }
      const priceBySku = await loadSellingPriceHintsBySku();
      const rows = await listInventoryGridRows(branchId, wantConsolidated, priceBySku);
      res.setHeader('Cache-Control', 'private, max-age=5');
      res.json({
        rows,
        count: rows.length,
        sellingPrices: Object.fromEntries(priceBySku),
      });
      // Persist zero price1 rows in background so next load / POS see DB prices.
      void persistSellingPricesFromHints(priceBySku).then((n) => {
        if (n > 0) {
          invalidateSellingHintsCache();
          if (typeof onProductsTableChange === 'function') onProductsTableChange();
        }
      }).catch((err) => console.warn('[PRODUCTS inventory-grid] persist prices:', err.message));
    } catch (error) {
      console.error('[PRODUCTS inventory-grid]', error);
      res.status(500).json({ error: 'Failed to load inventory grid' });
    }
  });

  // Get all products
  router.get('/', async (req, res) => {
    try {
      const branchId = resolveListBranchId(req, req.query.branchId);
      if (branchId === undefined) {
        return res.json([]);
      }
      const lightList =
        req.query.light === '1' ||
        req.query.light === 'true' ||
        req.query.listMode === 'inventory';
      const params = [];
      let query;

      if (branchId) {
        const branchKey = String(branchId).trim();
        const rows = await listProductsForBranch(branchKey, lightList);
        if (process.env.NODE_ENV !== 'production' && rows.length > 0) {
          console.log(`[PRODUCTS GET] branchId=${branchKey} light=${lightList} rows=${rows.length}`);
        }
        return res.json(rows);
      } else {
        query = `
          SELECT p.*,
            COALESCE(p.first_cost, p.cost) AS first_cost,
            COALESCE(p.last_cost, p.cost) AS last_cost,
            COALESCE(p.avg_cost, p.cost) AS avg_cost,
            p.stock AS stock
          FROM products p
          WHERE ${productActive('p')}
          ORDER BY p.name`;
      }

      const result = await db.query(query, params);
      const mainBranchIds = await loadMainBranchIds();
      const rows = dedupeProductsBySku(result.rows, undefined, mainBranchIds);
      if (process.env.NODE_ENV !== 'production' && rows.length > 0) {
        console.log(`[PRODUCTS GET] branchId=ALL light=${lightList} rows=${rows.length}`);
      }
      res.json(rows);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to fetch products' });
    }
  });

  /** Fill supplier from another row with the same SKU when this row has none. */
  async function enrichProductSupplierFromSku(row) {
    if (!row) return row;
    const hasId = row.supplier_id != null && String(row.supplier_id).trim() !== '';
    const hasName = row.supplier_name != null && String(row.supplier_name).trim() !== '';
    if ((hasId || hasName) || !row.sku || !String(row.sku).trim()) return row;

    const sibling = await db.query(
      `SELECT supplier_id, supplier_name
       FROM products
       WHERE LOWER(TRIM(COALESCE(sku, ''))) = LOWER(TRIM($1))
         AND (
           (supplier_id IS NOT NULL AND TRIM(COALESCE(CAST(supplier_id AS TEXT), '')) != '')
           OR (supplier_name IS NOT NULL AND TRIM(COALESCE(supplier_name, '')) != '')
         )
       ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST
       LIMIT 1`,
      [row.sku],
    );
    let src = sibling.rows[0];
    if (!src) {
      const bySku = await loadLatestPurchaseSupplierBySku();
      const hit = bySku.get(canonicalSkuString(row.sku).toLowerCase());
      if (hit) src = hit;
    }
    if (!src) return row;
    return {
      ...row,
      supplier_id: row.supplier_id || src.supplier_id || null,
      supplier_name: row.supplier_name || src.supplier_name || null,
    };
  }

  router.get('/low-stock', async (req, res) => {
    try {
      const branchId = req.query.branchId ? String(req.query.branchId).trim() : '';
      const params = [];
      let query = `
        SELECT id, sku, name, stock, min_stock, branch_id, unit
        FROM products
        WHERE ${coalesceActiveNotZero(db, 'is_active')}
          AND COALESCE(min_stock, 0) > 0
          AND COALESCE(stock, 0) <= COALESCE(min_stock, 0)`;
      if (branchId) {
        params.push(branchId);
        query += ` AND branch_id = $${params.length}`;
      }
      query += ' ORDER BY stock ASC NULLS FIRST, name ASC LIMIT 150';
      const result = await db.query(query, params);
      res.json(result.rows);
    } catch (error) {
      console.error('[PRODUCTS low-stock]', error);
      res.status(500).json({ error: 'Failed to fetch low-stock products' });
    }
  });

  router.get('/:id/deletable', async (req, res) => {
    try {
      const counts = await productTransactionCounts(req.params.id);
      res.json(counts);
    } catch (error) {
      console.error('[PRODUCTS deletable]', error);
      res.status(500).json({ error: 'Failed to check product transactions' });
    }
  });

  // Get single product (supplier resolved from sibling SKU rows when missing)
  router.get('/:id', async (req, res) => {
    try {
      const id = String(req.params.id || '').trim();
      if (!id) {
        return res.status(400).json({ error: 'Product id is required' });
      }
      const result = await db.query('SELECT * FROM products WHERE id = $1', [id]);
      if (!result.rows[0]) {
        return res.status(404).json({ error: 'Product not found' });
      }
      let row = result.rows[0];
      try {
        row = await enrichProductSupplierFromSku(row);
      } catch (enrichErr) {
        console.warn('[PRODUCTS GET/:id] supplier enrichment skipped:', enrichErr.message);
      }
      res.json(row);
    } catch (error) {
      console.error('[PRODUCTS GET/:id ERROR]', error);
      res.status(500).json({ error: 'Failed to fetch product' });
    }
  });

  // Create product
  router.post('/', requirePermission('inventory_create'), async (req, res) => {
    try {
      const { name, sku, barcode, category, price, price2, price3, price4, cost, stock, unit, taxRate, branchId, isActive, supplierId, supplierName } = req.body;
      const activeFlag = isActive !== false;
      const activeValue = db.engine === 'postgres' ? activeFlag : (activeFlag ? 1 : 0);

      const c = Number(cost) || 0;
      const resolvedBranchId = resolveProductBranchId(req, normalizeRequestedBranchId(branchId));
      if (resolvedBranchId === undefined) {
        return res.status(403).json({
          error: 'Sem filial atribuída para criar produtos. Selecione uma filial no inventário ou no formulário.',
        });
      }

      const skuTrim = String(sku || '').trim();
      if (!skuTrim) {
        return res.status(400).json({ error: 'Código (SKU) é obrigatório.' });
      }

      const existing = await findExistingProductForUpsert({
        sku: skuTrim,
        name: String(name || '').trim(),
        branchId: resolvedBranchId,
      });
      const storedBranchId = existing?.id
        ? await resolveStoredBranchId(resolvedBranchId)
        : await resolveStoredBranchIdForCreate(resolvedBranchId);

      if (existing?.id) {
        const canonicalSku =
          existing.matchedBy === 'name'
          && existing.existingSku
          && String(existing.existingSku).trim()
          && !skuLooksAutoGenerated(existing.existingSku)
            ? String(existing.existingSku).trim()
            : skuTrim;
        const result = await db.query(
          `UPDATE products
           SET name = $1, sku = $2, barcode = $3, category = $4, price = $5,
               price2 = COALESCE($6, price2),
               price3 = COALESCE($7, price3),
               price4 = COALESCE($8, price4),
               cost = $9, stock = COALESCE($10, stock), unit = $11, tax_rate = $12, is_active = $13,
               branch_id = $14,
               supplier_id = $15, supplier_name = $16,
               last_cost = COALESCE($9, last_cost), avg_cost = COALESCE($9, avg_cost),
               updated_at = CURRENT_TIMESTAMP
           WHERE id = $17
           RETURNING *`,
          [
            name, canonicalSku, barcode, category, price,
            Number(price2) > 0 ? Number(price2) : null,
            Number(price3) > 0 ? Number(price3) : null,
            Number(price4) > 0 ? Number(price4) : null,
            c, stock ?? null, unit || 'un', taxRate ?? DEFAULT_VAT_RATE, activeValue,
            storedBranchId,
            sanitizeUuid(supplierId), supplierName || null,
            existing.id,
          ],
        );
        await broadcastTable('products');
        return res.status(200).json(result.rows[0]);
      }

      const id = crypto.randomUUID();
      let result;
      try {
        // SQLite expands $10 four times from ONE param — do not pass c,c,c,c in the array.
        result = await db.query(
          `INSERT INTO products (id, name, sku, barcode, category, price, price2, price3, price4, cost, first_cost, last_cost, avg_cost, stock, unit, tax_rate, branch_id, is_active, supplier_id, supplier_name)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, $10, $10, $11, $12, $13, $14, $15, $16, $17)
           RETURNING *`,
          [
            id, name, skuTrim, barcode, category, price, price2 || 0, price3 || 0, price4 || 0,
            c,
            stock || 0, unit || 'un', taxRate ?? DEFAULT_VAT_RATE, storedBranchId, activeValue,
            sanitizeUuid(supplierId), supplierName || null,
          ],
        );
      } catch (insertErr) {
        if (!isUniqueSkuBranchError(insertErr)) throw insertErr;
        const conflict = await findProductBySkuAndBranch(db, skuTrim, resolvedBranchId);
        if (!conflict?.id) throw insertErr;
        result = await db.query(
          `UPDATE products
           SET name = $1, sku = $2, barcode = $3, category = $4, price = $5,
               price2 = COALESCE($6, price2),
               price3 = COALESCE($7, price3),
               price4 = COALESCE($8, price4),
               cost = $9, stock = COALESCE($10, stock), unit = $11, tax_rate = $12, is_active = $13,
               branch_id = $14,
               supplier_id = $15, supplier_name = $16,
               last_cost = COALESCE($9, last_cost), avg_cost = COALESCE($9, avg_cost),
               updated_at = CURRENT_TIMESTAMP
           WHERE id = $17
           RETURNING *`,
          [
            name, skuTrim, barcode, category, price,
            Number(price2) > 0 ? Number(price2) : null,
            Number(price3) > 0 ? Number(price3) : null,
            Number(price4) > 0 ? Number(price4) : null,
            c, stock ?? null, unit || 'un', taxRate ?? DEFAULT_VAT_RATE, activeValue,
            storedBranchId,
            sanitizeUuid(supplierId), supplierName || null,
            conflict.id,
          ],
        );
      }

      await broadcastTable('products');
      res.status(result.rows[0] ? 200 : 201).json(result.rows[0]);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      const msg = String(error?.message || '');
      if (isUniqueSkuBranchError(error)) {
        return res.status(409).json({
          error: 'Já existe um produto com este código (SKU) nesta filial ou catálogo partilhado.',
        });
      }
      if (/invalid input syntax for type uuid/i.test(msg)) {
        return res.status(400).json({
          error: 'Filial inválida. Selecione uma filial no inventário (ex.: Main Branch) e tente novamente.',
        });
      }
      if (/foreign key|violates foreign key/i.test(msg)) {
        return res.status(400).json({
          error: 'Dados de referência inválidos (filial ou fornecedor). Verifique e tente novamente.',
        });
      }
      res.status(500).json({
        error: msg ? `Failed to create product: ${msg}` : 'Failed to create product',
      });
    }
  });

  // Update product (with optimistic locking)
  router.put('/:id', requirePermission('inventory_edit'), async (req, res) => {
    try {
      const { id } = req.params;
      const existingResult = await db.query('SELECT * FROM products WHERE id = $1', [id]);
      if (!existingResult.rows[0]) {
        return res.status(404).json({ error: 'Product not found' });
      }
      const existing = existingResult.rows[0];
      const {
        name, sku, barcode, category, price, price2, price3, price4, cost, stock, unit, taxRate,
        branchId, isActive, version, supplierId, supplierName, lastCost, avgCost, preserveStock,
      } = req.body;
      const mergedName = name != null && name !== '' ? name : existing.name;
      const mergedSku = sku != null && sku !== '' ? sku : existing.sku;
      const mergedBarcode = barcode != null ? barcode : existing.barcode;
      const mergedCategory = category != null && category !== '' ? category : existing.category;
      const mergedPrice = price != null && price !== '' ? price : existing.price;
      // Price tiers 2-4: only overwrite when a positive value is supplied. A 0/blank means
      // "tier not set" for this request, so keep the stored value instead of wiping it
      // (purchase/stock/physical-count updates send these as 0).
      const mergedPrice2 = price2 != null && price2 !== '' && Number(price2) > 0 ? Number(price2) : existing.price2;
      const mergedPrice3 = price3 != null && price3 !== '' && Number(price3) > 0 ? Number(price3) : existing.price3;
      const mergedPrice4 = price4 != null && price4 !== '' && Number(price4) > 0 ? Number(price4) : existing.price4;
      const mergedCost = cost != null && cost !== '' ? cost : existing.cost;
      const mergedStock = stock != null && stock !== '' ? stock : existing.stock;
      const mergedUnit = unit != null && unit !== '' ? unit : existing.unit;
      const mergedTaxRate = taxRate != null && taxRate !== '' ? taxRate : existing.tax_rate;
      const mergedBranchId =
        resolveProductBranchId(req, branchId) ?? sanitizeUuid(branchId) ?? existing.branch_id;
      const mergedIsActive = isActive !== false && isActive !== 0 ? 1 : isActive === false || isActive === 0 ? 0 : existing.is_active;
      const mergedSupplierId = supplierId != null ? sanitizeUuid(supplierId) : existing.supplier_id;
      const mergedSupplierName = supplierName != null ? supplierName : existing.supplier_name;
      const keepStock = preserveStock === true || preserveStock === 'true' || preserveStock === 1;
      const setClause = keepStock
        ? `name=$1, sku=$2, barcode=$3, category=$4, price=$5, cost=$6, stock=stock,
           unit=$7, tax_rate=$8, branch_id=$9, is_active=$10,
           price2=$11, price3=$12, price4=$13,
           supplier_id=$14, supplier_name=$15,
           last_cost=COALESCE($16, last_cost), avg_cost=COALESCE($17, avg_cost)`
        : `name=$1, sku=$2, barcode=$3, category=$4, price=$5, cost=$6, stock=$7,
           unit=$8, tax_rate=$9, branch_id=$10, is_active=$11,
           price2=$12, price3=$13, price4=$14,
           supplier_id=$15, supplier_name=$16,
           last_cost=COALESCE($17, last_cost), avg_cost=COALESCE($18, avg_cost)`;
      const updateParams = keepStock
        ? [mergedName, mergedSku, mergedBarcode, mergedCategory, mergedPrice, mergedCost, mergedUnit, mergedTaxRate,
           mergedBranchId,
           mergedIsActive,
           mergedPrice2 || 0, mergedPrice3 || 0, mergedPrice4 || 0,
           mergedSupplierId, mergedSupplierName || null,
           lastCost ?? null, avgCost ?? null]
        : [mergedName, mergedSku, mergedBarcode, mergedCategory, mergedPrice, mergedCost, mergedStock, mergedUnit, mergedTaxRate,
           mergedBranchId,
           mergedIsActive,
           mergedPrice2 || 0, mergedPrice3 || 0, mergedPrice4 || 0,
           mergedSupplierId, mergedSupplierName || null,
           lastCost ?? null, avgCost ?? null];
      
      let result;
      if (version != null) {
        result = await db.query(
          `UPDATE products 
           SET ${setClause},
               version = version + 1
           WHERE id=$${updateParams.length + 1} AND version=$${updateParams.length + 2}
           RETURNING *`,
          [...updateParams, id, version]
        );
        if (!checkOptimisticLock(result, res, 'Product')) return;
      } else {
        result = await db.query(
          `UPDATE products 
           SET ${setClause}
           WHERE id=$${updateParams.length + 1}
           RETURNING *`,
          [...updateParams, id]
        );
        if (result.rowCount === 0) {
          return res.status(404).json({ error: 'Product not found' });
        }
      }
      
      const updated = result.rows[0];
      const skuKey = String(updated?.sku || '').trim();
      if (skuKey) {
        if (taxRate != null && taxRate !== '') {
          await db.query(
            `UPDATE products
             SET tax_rate = $1, updated_at = CURRENT_TIMESTAMP
             WHERE ${coalesceActiveNotZero(db, 'is_active')}
               AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($2)`,
            [Number(taxRate), skuKey]
          );
        }
        if (price != null && price !== '') {
          // Propagate the price tiers to every branch row sharing this SKU, but never
          // overwrite an existing tier with 0/blank: routine updates (purchases, stock
          // adjustments, physical counts) send price2-4 = 0 and would otherwise wipe them.
          // Pass null (not 0) for "no value" so COALESCE keeps the stored tier. Do NOT use
          // a `$n > 0` test: PostgreSQL infers such a param as integer and rejects decimal
          // tiers (e.g. 739.98) with "invalid input syntax for type integer".
          const skuTier = (v) => (Number(v) > 0 ? Number(v) : null);
          await db.query(
            `UPDATE products
             SET price = $1,
                 price2 = COALESCE($2, price2),
                 price3 = COALESCE($3, price3),
                 price4 = COALESCE($4, price4),
                 updated_at = CURRENT_TIMESTAMP
             WHERE ${coalesceActiveNotZero(db, 'is_active')}
               AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($5)`,
            [Number(price), skuTier(price2), skuTier(price3), skuTier(price4), skuKey]
          );
        }
        const costVal = cost != null && cost !== '' ? Number(cost) : null;
        if (costVal != null && !Number.isNaN(costVal)) {
          const lastVal = lastCost != null && lastCost !== '' ? Number(lastCost) : costVal;
          const avgVal = avgCost != null && avgCost !== '' ? Number(avgCost) : costVal;
          await db.query(
            `UPDATE products
             SET cost = $1, last_cost = $2, avg_cost = $3, updated_at = CURRENT_TIMESTAMP
             WHERE ${coalesceActiveNotZero(db, 'is_active')}
               AND LOWER(TRIM(COALESCE(sku, ''))) = LOWER($4)`,
            [costVal, lastVal, avgVal, skuKey],
          );
        }
      }

      invalidateSellingHintsCache();
      await broadcastTable('products');
      res.json(updated);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to update product' });
    }
  });

  // Update stock
  router.patch('/:id/stock', requirePermission('inventory_adjust'), async (req, res) => {
    try {
      const { id } = req.params;
      const { quantityChange } = req.body;
      
      const result = await db.query(
        'UPDATE products SET stock = stock + $1 WHERE id = $2 RETURNING *',
        [quantityChange, id]
      );
      
      await broadcastTable('products');
      res.json(result.rows[0]);
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to update stock' });
    }
  });

  // Batch import products (SQLite + PostgreSQL)
  router.post('/batch', requirePermission('inventory_import', 'inventory_create'), async (req, res) => {
    try {
      const { products: productList } = req.body;
      if (!Array.isArray(productList) || productList.length === 0) {
        return res.status(400).json({ error: 'products array is required' });
      }

      let inserted = 0;
      let updated = 0;
      let failed = 0;
      const errors = [];

      for (const p of productList) {
        const rawSku = String(p?.sku ?? p?.codigo ?? p?.code ?? '').trim();
        const rawName = String(p?.name ?? p?.descricao ?? p?.description ?? p?.designacao ?? '').trim();
        const branchId = resolveProductBranchId(req, p.branchId);
        if (branchId === undefined) {
          failed += 1;
          errors.push({ sku: rawSku || rawName || '?', error: 'Sem filial atribuída' });
          continue;
        }
        const cost = Number(p.cost) || 0;
        const stock = Number(p.stock ?? p.quantidade) || 0;
        const activeInt = p.isActive !== false ? 1 : 0;

        let sku = rawSku;
        let existingId = null;
        let existingMatch = null;

        if (sku || rawName) {
          existingMatch = await findExistingProductForUpsert({
            sku: rawSku,
            name: rawName,
            branchId,
          });
        }

        if (existingMatch?.id) {
          existingId = existingMatch.id;
          if (existingMatch.existingSku && String(existingMatch.existingSku).trim()) {
            sku = String(existingMatch.existingSku).trim();
          } else if (!sku) {
            sku = rawName;
          }
        } else if (!sku && rawName) {
          sku = `AUTO-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        }

        if (!sku) {
          sku = `AUTO-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        }
        const name = rawName || sku;
        const storedBranchId = await resolveStoredBranchId(branchId);

        try {
          if (existingId) {
            const upd = await db.query(
              `UPDATE products
               SET name = $1, sku = $2, barcode = $3, category = $4, price = $5, cost = $6,
                   stock = $7, unit = $8, tax_rate = $9, branch_id = $10,
                   supplier_id = $11, supplier_name = $12, is_active = $13,
                   last_cost = COALESCE($6, last_cost), avg_cost = COALESCE($6, avg_cost),
                   updated_at = CURRENT_TIMESTAMP
               WHERE id = $14`,
              [
                name,
                sku,
                p.barcode || '',
                p.category || 'GERAL',
                Number(p.price) || 0,
                cost,
                stock,
                String(p.unit || p.unidade || 'UN'),
                Number(p.taxRate ?? p.iva) || DEFAULT_VAT_RATE,
                storedBranchId,
                sanitizeUuid(p.supplierId),
                p.supplierName || null,
                activeInt,
                existingId,
              ],
            );
            if (upd.rowCount > 0) updated++;
          } else {
            const id = crypto.randomUUID();
            const ins = await db.query(
              `INSERT INTO products (id, name, sku, barcode, category, price, price2, price3, price4, cost, first_cost, last_cost, avg_cost, stock, unit, tax_rate, branch_id, is_active, supplier_id, supplier_name)
               VALUES ($1, $2, $3, $4, $5, $6, 0, 0, 0, $7, $7, $7, $7, $8, $9, $10, $11, $12, $13, $14)`,
              [
                id,
                name,
                sku,
                p.barcode || '',
                p.category || 'GERAL',
                Number(p.price) || 0,
                cost,
                stock,
                String(p.unit || p.unidade || 'UN'),
                Number(p.taxRate ?? p.iva) || DEFAULT_VAT_RATE,
                storedBranchId,
                activeInt,
                sanitizeUuid(p.supplierId),
                p.supplierName || null,
              ],
            );
            if (ins.rowCount > 0) inserted++;
          }
        } catch (err) {
          failed++;
          const rowError = err?.message || String(err);
          console.error('[PRODUCTS IMPORT ROW ERROR]', rowError, { sku });
          errors.push({ sku, error: rowError });
        }
      }

      console.log(`[PRODUCTS IMPORT] inserted=${inserted} updated=${updated} failed=${failed}`);
      await broadcastTable('products');
      res.status(201).json({ imported: inserted, updated, failed, errors: errors.slice(0, 50) });
    } catch (error) {
      console.error('[PRODUCTS BATCH ERROR]', error);
      res.status(500).json({ error: 'Failed to batch import products' });
    }
  });

  // Delete product (soft delete) — only when no stock movements or sales exist
  router.delete('/:id', async (req, res) => {
    try {
      const { id } = req.params;
      const counts = await productTransactionCounts(id);
      if (!counts.deletable) {
        return res.status(409).json({
          error: 'Product has stock movements or sales and cannot be deleted',
          ...counts,
        });
      }

      await db.query('UPDATE products SET is_active = false WHERE id = $1', [id]);

      await broadcastTable('products');
      res.json({ success: true });
    } catch (error) {
      console.error('[PRODUCTS ERROR]', error);
      res.status(500).json({ error: 'Failed to delete product' });
    }
  });

  return router;
};
